### ISSUE TITLE
Bug in your code causes unnecessary waste in storing state_dict weights

### ISSUE THREAD

**Issue by PeterL1n** [ZHKKKe/MODNet#102]
In your MODNet class, you should not set `self.backbone` if backbone is not used anywhere else in that class. You pass the backbone to LRBranch and LRBranch set `self.backbone` again. So the same mobilenet backbone is referred twice in two different model. When you save state_dict, the weights will be copied twice! If you inspect your state_dict you will find out.

Rather, you should just create the backbone in MODNet class and pass it to LRBranch, no need to set `self.backbone` in the MODNet class to avoid this issue.

**Comment by ZHKKKe** [comment]
Hi, thanks for your suggestion. 
We will indicate this in the next update.
However, since some steps are required to prepare a new pre-trained model, we plan to retain the existing code for future research.

**Comment by PeterL1n** [comment]
You don't need to retrain! Just modify the code, and manually change the state_dict (Load the state dict, edit it like a regular python dictionary to match with the new names, and save it again).

Or even simpler. Remove the self.backbone reference from MODNet class. Load it using `load_state_dict(state_dict, strict=False)`. Setting `strict=False` will allow pytorch to ignore state_dict items that don't match, and then save the state_dict again.

**Comment by ZHKKKe** [comment]
@PeterL1n 
Yep. Thanks. 
However, we also need to prepare the model for ONNX
