### ISSUE TITLE
关于骨干网络数据集的问题

### ISSUE THREAD

**Issue by upperblacksmith** [ZHKKKe/MODNet#104]
您好，在您的文章中有提到使用了the Supervisely Person Segmentation这个数据集训练了骨干网络，
1.请问是下面链接的这个数据集吗？
[https://supervise.ly/explore/projects/supervisely-person-dataset-23304/datasets](url)
2.您是直接在这个数据集上训练骨干网络的吗？或者说使用了某个预训练模型？
3.这个数据集好像不能直接下载，是否有别的途径下载该数据集
期待您的帮助和解答，谢谢。

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。
我们使用的预训练模型来自一个开源Github仓库：https://github.com/thuyngch/Human-Segmentation-PyTorch
请访问仓库主页获取更多信息。
