### ISSUE TITLE
压根就做不到实时呀

### ISSUE THREAD

**Issue by zhanghonglishanzai** [ZHKKKe/MODNet#106]
view_np = matte_np * frame_np + (1 - matte_np) * frame_dy

只这步就得25~28ms，我们就拿26来算，也就38帧，是怎么得到一秒钟63帧的，而且分辨率好低，如果用HD或者4K的视频，

吓死个人好吧

 _, _, matte_tensor = modnet(frame_tensor, True)  

这步确实是快，14ms，只按照这个算的话，一秒钟可以71帧，但是不能这么算啊

我就不说modnet = MODNet(backbone_pretrained=False)

modnet.load_state_dict(torch.load(pretrained_ckpt))这两部分了

求作者给个指点呀

我微信nangongqiuhan003

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。

对于你的问题：
**Q1: 是怎么得到一秒钟63帧的**
我们测试的63帧是采用GTX1080Ti GPU, 在512x512的分辨率下测试的。测试的时间包括`数据读取和网络预测`。上面提到的合成步骤是不包括的。

**Q2: 而且分辨率好低，如果用HD或者4K的视频**
目前的解决方案无法处理HD或者4K视频。我们的论文中仅提到可以在512分辨率+GPU下做到实时。如果需要处理HD或者4k，请参考Background Matting V2 论文。

**Q3: 我就不说modnet = MODNet(backbone_pretrained=False) modnet.load_state_dict(torch.load(pretrained_ckpt))这两部分了**
模型的加载只在运行开始时执行，它只会运行一次。在后续测试中（除了第一张图片）不需要这一步。

此外，这个库中的代码仅用于研究目的，所以没有进行一系列的优化。
我们使用C++调用ONNX模型可以在普通CPU上以20+FPS运行，进一步优化过的网络可以达到30+FPS。
这些解决方案预计将在未来的1-2个月发布。

**Comment by ZHKKKe** [comment]
@StarkerRegen 
你好。我们的测试使用Ubuntu 16.04 系统。CPU为 intel i7-8700K。
我们将模型的参数和输入转化为FP16类型，并删除了所有不必要的输出层。
此外，数据读取和推论是使用两个进程完成的。

**Comment by zhanghonglishanzai** [comment]
您好，我是直接调用你们训练好的预训练模型，并没有自己去重新训练模型


在matting函数中，两次resize确实占用了大量的时间


我想问一下，你们有没有注意到这个问题，以及如何改进的，下面是我查到的相关资料




https://www.it1352.com/900587.html










------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月11日(星期二) 上午10:44
收件人: ***@***.***&gt;; 
抄送: "Microsoft ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZHKKKe/MODNet] 压根就做不到实时呀 (#106)





  
@StarkerRegen
 你好。我们的测试使用Ubuntu 16.04 系统。CPU为 intel i7-8700K。
 我们将模型的参数和输入转化为FP16类型，并删除了所有不必要的输出层。
 同时，在CPU运行下我们将输入分辨率减小为了448x448。
 此外，数据读取和推论是使用两个进程完成的。
  
作者您好，请检查一下您在CPU下做测试时是否保证GPU没有被调用。根据github上的代码，我在本机上做摄像头在线测试时，虽然指定了只使用CPU，但是GPU还是被调用了:(

**Comment by czHappy** [comment]
> @StarkerRegen
> 你好。我们的测试使用Ubuntu 16.04 系统。CPU为 intel i7-8700K。
> 我们将模型的参数和输入转化为FP16类型，并删除了所有不必要的输出层。
> 同时，在CPU运行下我们将输入分辨率减小为了448x448。
> 此外，数据读取和推论是使用两个进程完成的。
@ZHKKKe 
请问CPU下如何使用FP16，我做了实验貌似CPU下不能使用.half()操作，但是GPU下可以？

**Comment by ZHKKKe** [comment]
@czHappy 
你好，我上述提到的测试均是使用C++运行ONNX版本已经MNN版本的。Python + Pytorch在CPU下目前不支持.half()操作。

**Comment by ZHKKKe** [comment]
@zhanghonglishanzai 
你好，resize操作确实很慢。这一点我们也在尝试对C++/WebAssembly版本优化。Python下的优化相对困难。
`view_np = matte_np * np.full(frame_np.shape, 255.0)`的效率是很低的。我们目前没有针对Python版本的优化。
如果你使用C++, 用并行for循环或者写一个cuda模块应该会快很多。
