### ISSUE TITLE
Sharing a TensorRT implementation of MODNet

### ISSUE THREAD

**Issue by jkjung-avt** [ZHKKKe/MODNet#107]
@ZHKKKe  Thanks for sharing your inference code and the pre-trained model.

I took your pre-trained PyTorch model and was able to build a TensorRT engine from it.  I shared my TensorRT implementation at [jkjung-avt/tensorrt_demos](https://github.com/jkjung-avt/tensorrt_demos), or more specifically, [Demo \#7: MODNet](https://github.com/jkjung-avt/tensorrt_demos#modnet).  Feel free to give it a try.

**Comment by ZHKKKe** [comment]
@jkjung-avt 
It is wonderful! Thanks!
I hope to integrate it into this Github project after I check it.
As I am busy these two weeks, I will add it later. See what you think.

**Comment by jkjung-avt** [comment]
> I hope to integrate it into this GitHub project after I check it.

I put my code under MIT License.  You are welcome to integrate the code into this repo by following the license.

Thank you again for sharing the model.

**Comment by ZHKKKe** [comment]
Hey, I referenced your project in our README. Thanks again.
