### ISSUE TITLE
Internal Server Error is Gradio

### ISSUE THREAD

**Issue by ddiddu** [ZHKKKe/MODNet#109]
Hello, 
first thanks for your great repository.

I want to try WebGUI for Image Matting, but the WebGUI link hosted by Gradio results to Internal Server Error.

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Will you be able to fix it?
Thank you.

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.
The Gradio team changed the link of WebGUI. Please try: https://www.gradio.app/hub/aliabd/modnet 
I have also updated it in README.

**Comment by ddiddu** [comment]
Thank you!
