### ISSUE TITLE
Any way to run the model in Tensorflow / Tensorflow.js?

### ISSUE THREAD

**Issue by msurguy** [ZHKKKe/MODNet#11]
Hi! 
I'm not very experienced with ML yet and was wondering if you could point me towards ability to run the trained model inference using Tensorflow / TF.js. What would I need to do? 

Thanks so much for the paper and the model!

**Comment by ZHKKKe** [comment]
Hi. Thanks for your attention.

I am sorry that I also have no idea about how to run PyTorch pre-trained model by using Tensorflow. You may need to define the model architecture by TF and use some tools to convert the pre-trained model to the TF format. 
Besides, duo to various reasons, we have no plan to release the TF version of this work.
