### ISSUE TITLE
同色构图不完整，请问是什么情况？如何修复此类问题呢

### ISSUE THREAD

**Issue by zxbit2011** [ZHKKKe/MODNet#112]
大佬，请教一下：

1、就算是同色的图片进行构图，还是存在抠图不完全的情况？
2、头发边缘颜色与背景重叠，如何修复这种问题？

谢谢

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。

请问：
1. 输入的图片面部是否带有马赛克？
2. 是否尝试使用我们的[WebGUI](https://www.gradio.app/hub/aliabd/modnet)测试结果？

**Comment by zxbit2011** [comment]
1、输入的图片没有马赛克，只是提交问题的时候打的。
2、已尝试还是会出现这个问题。
谢谢

**Comment by vandesa003** [comment]
请问如果输入图片在非人像部分有马赛克或者其他纹理，会对网络有什么影响么？

**Comment by ZHKKKe** [comment]
@zxbit2011 
你好，这可能是由于我们的预训练模型在训练时没有涵盖这类数据。
可以尝试使用我们发布在[这个网站](https://sight-x.cn/portrait_matting)的新版模型处理该图片。

**Comment by zxbit2011** [comment]
> @zxbit2011
> 你好，这可能是由于我们的预训练模型在训练时没有涵盖这类数据。
> 可以尝试使用我们发布在[这个网站](https://sight-x.cn/portrait_matting)的新版模型处理该图片。

是好很多了，目前边缘头发颜色如何消除色差，就如removebg效果，有什么思路没？

**Comment by ZHKKKe** [comment]
@zxbit2011 
removebg的结果看起来是对结果(1) 做一个erode操作，并(2) 计算前景色来消除边缘颜色。这些属于后处理步骤。

**Comment by zxbit2011** [comment]
> @zxbit2011
> removebg 的结果看起来是对结果(1) 做一个腐蚀操作，并(2) 计算前视图来删除边界颜色。这些后处理步骤。

你好，非常感谢你的回复，对边缘处理有一定的效果。如何仅针对前景图片的边缘进行腐蚀？现在这种方式导致脸部所有前景都被腐蚀了。
````
kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (3, 3))
# 腐蚀
foreground_img = cv2.erode(foreground_img, kernel)   
````
