### ISSUE TITLE
The ONNX model would crash when used for image larger than 512 pixels (either width or height) for inference

### ISSUE THREAD

**Issue by qunliu** [ZHKKKe/MODNet#113]
I was testing out the ONNX model inference with some sample videos, and found out even though the model allows image input with any width or heigh, but it'd crash on my machine when I feed in any image that's larger than 512 pixels (either width or height). Is this a known issue? Is there any workaround? Thanks!

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention, and sorry for late response.

There are two possible problems that may cause the crash:
1. Have you resized the input image to ensure its sides can be divided by 32?
2. Dose your machine have enough memory (a large input size will use more memory) ?

**Comment by qunliu** [comment]
Thanks for the heads-up! That's good to know. My current workaround is to resize it to 512 or smaller (keeping the aspect ratio), this may have image quality loss especially when I have high-res images. I will give it a try to resize it as little as possible and still a factor of 32 and see if that helps. I have a pretty decent machine and hope the memory isn't a bottleneck for regular size images (eg: 4K or less), but will find out.
