### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by newjavaer** [ZHKKKe/MODNet#114]
Hi，Excuse me. I have some question about the paper and experiment.
     1.Have you test or train on the dateset DIM-493. And if you have done ，how is the result?
     2.As you said in paper , the dp maybe have some erros(Although dp may contain inaccurate values for the pixels with md= 0,it has high precision for the pixels with md= 1.),
        it doesn't effect the result of the feacture fusion?Why?I think the pixels with md = 0 will do some wrong effect on the Sp feature map.
     3. What do you think is the difference between  task matting on some semitransparent thing（net,glass,plastic bag）and matting on the portrait？
Hope for your reply!

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention, and sorry for late response.

For your questions:
**Q1: Have you test or train on the dateset DIM-493. And if you have done, how is the result?**
Sorry that we do not train the model on DIM-493.

**Q2: it doesn't effect the result of the feacture fusion?Why?I think the pixels with md = 0 will do some wrong effect on the Sp feature map.**
We add an constraint for the final alpha matte, the fusion of d_p and s_p is learned by the network, i.e., the network will select the more correct pixels. However, some times, the undesired details from d_p may be selected and affect the final alpha matte. It is possible.

**Q3: What do you think is the difference between task matting on some semitransparent thing（net,glass,plastic bag）and matting on the portrait**
You may can regard the hair regions of the portrait as semi-transparent things. Learning a general matting model for all semi-transparent things is much difficult than focusing on portraits.
