### ISSUE TITLE
关于modnet.torchscript模型部署问题

### ISSUE THREAD

**Issue by fengdian8564** [ZHKKKe/MODNet#119]
您好，感谢您的研究成果，非常有帮助。请教一个问题，现在我想用libtorch1.7.1+cu110版本来调用cpu版本的modnet.torchscript，在生成脚本export_torchscript.py中，去掉了（第40行）modnet = nn.DataParallel(modnet).cuda()中.cuda()的部分。

而在调用过程中 采用C++执行auto outputs = model.forward({ src }).toTuple()->elements();时出现错误，src是输入图像，已经仿照python代码将格式转化为[batch, 512, 512, c]格式的张量，且将src转化为-1~1之间的浮点类型。但在执行过程中报错如图所示。
![image](https://user-images.githubusercontent.com/38320205/123796958-42e9e780-d918-11eb-9076-441fa802b227.png)

麻烦请问下该怎么处理这种情况，是否是模型转换上出了问题，还是libtorch的版本出现了问题。希望能在不久得到您的答复，再次感谢。

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。

输入的张量形状应该为[batch, c, h, w].

**Comment by fengdian8564** [comment]
> 你好，感谢你的关注。
> 
> 输入的张量形状应该为[batch, c, h, w].

您好，不好意思，是我提问的时候输入错了，输入的张量是没有问题的，张量类型是[b,c,h,w]。我尝试创造随机的[1,3,512,512]维度，范围在[-1,1]之间，并用trace来转化script。提示出错如下：
![image](https://user-images.githubusercontent.com/38320205/124047858-99097880-da47-11eb-9453-f16efbac6cf7.png)

**Comment by ZHKKKe** [comment]
日志似乎是在说使用的运行时环境不支持`Scatter`操作。
可能与TorchScript的C++运行环境有关。抱歉，我对此没有太多的经验。

**Comment by fengdian8564** [comment]
> 日志似乎是在说使用的运行时环境不支持`Scatter`操作。
> 可能与TorchScript的C++运行环境有关。抱歉，我对此没有太多的经验。

好的，非常感谢，我再尝试看看，是否是模型转换的时候出了什么问题
