### ISSUE TITLE
Provide user video

### ISSUE THREAD

**Issue by bluesky314** [ZHKKKe/MODNet#12]
The colab notebook uses user's webcam video. How can we provide a pre-recorded video file for inference?

**Comment by ZHKKKe** [comment]
Hi. Tanks for your attention. 

I am sorry that current demo does not support this feature. Since many requirements about it are received, we plan to support it in the next week.

If you want to do it now, you have to split your video to independent frames and process them by image matting demo.

**Comment by bluesky314** [comment]
How is the temporal information or previous history taken into account if we are passing in frame by frame?

**Comment by ZHKKKe** [comment]
In this work, we do not consider temporal informations, we only divide the video into frames and process them as image matting. Therefore, video matting is an application of MODNet.
