### ISSUE TITLE
开源模型效果为何和商用模型效果差这么多呢？

### ISSUE THREAD

**Issue by imliupu** [ZHKKKe/MODNet#120]
您好，首先感谢您提供的开源模型。

经测试发现开源模型与论文给出的效果有较大的差距，是否开源模型只是一个未训练完成的demo？
以开源模型和商用模型的效果差这么多呢？
是训练所用的数据集体量不一样吗？还是模型结构和训练方式有所优化呢？能否提供一个大概的思路，感谢！

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。
抱歉回复晚了。

开源模型的训练详情和使用的数据如论文所述。
商用模型对模型结构进行了优化改进，添加了新的子目标，使用了更大的数据集，采用了更复杂的训练策略。

**Comment by semchan** [comment]
请问，再商用检测的时候，是否先做人物的检测呢？谢谢

**Comment by ZHKKKe** [comment]
@semchan 
你好，人物检测是作为一个子目标包含在了模型中的。

**Comment by SeanChanCXG** [comment]
> 你好，感谢你的关注。
> 抱歉回复晚了。
> 
> 开源模型的训练详情和使用的数据如论文所述。
> 商用模型对模型结构进行了优化改进，添加了新的子目标，使用了更大的数据集，采用了更复杂的训练策略。

你好，感谢作者的分享。

**Comment by SeanChanCXG** [comment]
> 你好，感谢你的关注。
> 抱歉回复晚了。
> 
> 开源模型的训练详情和使用的数据如论文所述。
> 商用模型对模型结构进行了优化改进，添加了新的子目标，使用了更大的数据集，采用了更复杂的训练策略。

感谢作者的分享！

**Comment by cxgincsu** [comment]
> 你好，感谢你的关注。
> 抱歉回复晚了。
> 
> 开源模型的训练详情和使用的数据如论文所述。
> 商用模型对模型结构进行了优化改进，添加了新的子目标，使用了更大的数据集，采用了更复杂的训练策略。

感谢作者的分享！
测试中发现模型背景误扣比较多，请问作者是否能够详细描述下新的子目标及训练策略思路。另外新的模型能够获取到吗，非常感谢！！

**Comment by ZHKKKe** [comment]
@cxgincsu 
你好，目前新模型只能通过商业授权获取。

**Comment by liuflya** [comment]
> 您好，首先感谢您提供的开源模型。
> 
> 经测试发现开源模型与论文给出的效果有较大的差距，是否开源模型只是一个未训练完成的demo？ 以开源模型和商用模型的效果差这么多呢？ 是训练所用的数据集体量不一样吗？还是模型结构和训练方式有所优化呢？能否提供一个大概的思路，感谢！

同问，使用开源模型测试PPM-100得到的结果与论文所给的指标还有可视化结果都差的很大

**Comment by MZener** [comment]
> @zhangzscn 您好，关于商用授权，请通过邮箱联系，谢谢。

大佬，三年过去了，这个网站版本的模型能否开源下呢？
