### ISSUE TITLE
关于训练数据集的挑选准则

### ISSUE THREAD

**Issue by andy910389** [ZHKKKe/MODNet#121]
你好 想请问关于在MODnet模型中所使用的训练数据集，
目前得知因为有Licence问题，所以训练集不会发布
也知道你们是自己搜集人物影像，并利用photoshop标注。
我想请教的是:
1. 此训练集中半身跟全身影像的比例?
2. 从issue上面得知，你们是搜集3000张前景，与30张(512*512)的背景，以不同比例的方式将前景合成到背景中，
最后共获得90000张图片去训练，这样对吗?
3. 此训练集中的影像是连续的frame，还是非连续的? 或者是部分影像是连续的?
4. 此训练集中的影像的前景跟背景的分辨率大概都是多少? 因为从您发布的PPM-100中，发现几乎都是将近2K到4K
这让我猜测您的训练集中是否也是从2K到4K的分辨率的影像去缩放到512*512来训练的?
5. 请问你们在transform中用了哪些data argumentation的技巧，从Issue中大致只能得知有用到水平翻转以及ColorJitter，
是否还有其他的?可否提供详细的transform信息参考? 
谢谢

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。

对于你的问题：
1. 论文中使用的训练集大部分为半身像（~3000张），只有少量的全身像（~300张）
2. 对的。每个前景会和30个不同的背景合成，背景的原始大小也大于512x512
3. 都是单独的图片
4. 前景分辨率为1080p左右。北京分辨率覆盖约为512px~2k
5. 训练时没有其他特别的augmentation技巧

**Comment by andy910389** [comment]
> 你好，感谢你的关注。
> 
> 对于你的问题：
> 
> 1. 论文中使用的训练集大部分为半身像（~3000张），只有少量的全身像（~300张）
> 2. 对的。每个前景会和30个不同的背景合成，背景的原始大小也大于512x512
> 3. 都是单独的图片
> 4. 前景分辨率为1080p左右。北京分辨率覆盖约为512px~2k
> 5. 训练时没有其他特别的augmentation技巧

谢谢您的回复，关于transform，因为我注意到我发现其他相关研究，都会运用水平翻转、色相转换或旋转等等..
但您的意思在您的这个model中，是除了基本的ToTensor和Normalize，没有额外应用其他的翻转或ColorJitter技巧吗?
transforms.ToTensor(),
transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),

**Comment by ZHKKKe** [comment]
@andy910389 
我们的训练数据在合成的时候添加了ColorJitter等技巧。同时训练时候也会有水平翻转等增强。
目前发布的代码为测试代码，在测试的时候，不会使用这些技巧进行数据预处理。

**Comment by dpcq** [comment]
合成数据有相关代码吗？可以提供一下吗？

**Comment by ZHKKKe** [comment]
@dpcq 
抱歉，目前我们无法开源数据合成相关代码。
你可能可以参考一些以往工作开源的数据合成代码，如[DIM](https://github.com/foamliu/Deep-Image-Matting)
