### ISSUE TITLE
tendor.expand_as(x) issue

### ISSUE THREAD

**Issue by Leeviber** [ZHKKKe/MODNet#122]
Hi author,

I met one issus regarding model transfer. I need transfer onnx the model to the rknn format for edge devices deploying. However, rknn is not support expand_as or expand opts such as ` w.expand_as(x)`.

Is it okay to replace using `w.repeat(1,1,8,8)`, because the shape of w is (1,1280,8,8) and shape of x is (1,1280,1,1)

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

I think that using `repeat` has the same result. You may can try it :)
