### ISSUE TITLE
关于输入512*512的图片

### ISSUE THREAD

**Issue by Fight-hawk** [ZHKKKe/MODNet#124]
你好，首先感谢开源如此优秀的论文。这里有几个疑问，希望作者能简单解答一下
1.首先输入图片是如何变换到512*512的，直接resize还是随机crop，又或者是其他方法
2.其次关于合成数据背景图片的选择，是否会避开那写有人的图片

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。
1. 我们在合成时候就会对前景及背景进行缩放到512。
2. 是的，背景图会通过人脸识别去掉有人的图。

**Comment by ZHKKKe** [comment]
@Fight-hawk 
对于你的问题：
**Q1: 合成的时候缩放 指的是先把前景和背景都缩放到512，然后进行合成，还是先合成再缩放**
先缩放到768左右，然后合成，再crop至512.
**Q2: 直接缩放到512*512就会发生形变啊，为什么不用crop呢**
请参考Q1.

**Comment by aceyw** [comment]
作者您好，
上面Q1解答说“先缩放到768左右，然后合成，再crop至512.”
请问，768里crop512，具体是什么流程呢？ 直接crop的话，会出现把人脸部分区域crop掉的情况吧？

**Comment by ZHKKKe** [comment]
@aceyw 
是通过matte 计算出 bbox做为参考，然后进行crop的。有一些图会将人脸部分截取掉。
