### ISSUE TITLE
modnet_photographic_portrait_matting.ckpt和modnet_webcam_portrait_matting.ckpt这两个预训练模型有何不同?

### ISSUE THREAD

**Issue by pango99** [ZHKKKe/MODNet#125]
你好，请问这两个预训练模型有什么区别？是训练数据集不同是吗?

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。
modnet_photographic_portrait_matting.ckpt：模型在论文所属的标注数据集上进行训练。
modnet_webcam_portrait_matting.ckpt：将上述模型作为预训练，使用由电脑摄像头采集的数据进行SOC训练适应后的模型。

**Comment by pango99** [comment]
那是不是说modnet_webcam_portrait_matting一般用于视频,modnet_photographic_portrait_matting则用于图片?

**Comment by ZHKKKe** [comment]
@pango99 
是的，我们提供的两个demo分别用于图片和视频的测试。

**Comment by ToBigboss** [comment]
> @pango99
> 是的，我们提供的两个demo分别用于图片和视频的测试。

我测试图片，发现modnet_webcam_portrait_matting比modnet_photographic_portrait_matting效果还差
