### ISSUE TITLE
同样的图片，为何用离线Demo抠像的结果和在网站抠像的结果不一样？

### ISSUE THREAD

**Issue by pango99** [ZHKKKe/MODNet#127]
你好，下面这样图片是我运行项目中的demo.video_matting.webcam.run程序的结果，可以看到背景里的椅子被错误地抠进人像

![MODNet - WebCam  Press 'Q' To Exit](https://user-images.githubusercontent.com/6065571/128724516-16db44a2-dee0-4afd-9d05-bf54eec09f2c.png)

然后我裁剪出左边摄像头视频图片，上传给[抠像网站](https://sight-x.cn/portrait_matting/) 做抠像，发现人像可以被干净地抠出，椅子不会被认为是人像，下图是网站抠像的结果
![download](https://user-images.githubusercontent.com/6065571/128724972-570a0718-9bd4-45b5-9a88-970696e86deb.png)

所以请问下为何同样一张图片，项目里的Demo的精度不如抠像网站？他们是用不同的模型是吗？抠像网站是用哪个模型?

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。
Demo里的模型是为研究目的提供的。
网站里使用的模型进行了进一步优化，模型没有开源。

**Comment by pango99** [comment]
哦，那如何能取得网站的模型？是不是需要购买License?

**Comment by ZHKKKe** [comment]
@ZHKKKe 如果需要网站中的模型，请通过邮件与我联系。

**Comment by ZHKKKe** [comment]
@pango99 如果需要网站中的模型，请通过邮件与我联系。

**Comment by kkkkkkun** [comment]
离线模型，有手机可用的版本吗？

**Comment by lovejing0306** [comment]
> @pango99 如果需要网站中的模型，请通过邮件与我联系。
请问您的邮箱是多少？

**Comment by ZHKKKe** [comment]
@lovejing0306
网站中的模型为商用版，需要购买license.
请直接联系 kezhanghan@outlook.com.

**Comment by spxie** [comment]
@ZHKKKe ，你好，我想获得商用版授权，向  kezhanghan@outlook.com 发邮件了，但是没有回复是什么情况
