### ISSUE TITLE
about  run webcam\run.py --video is the RTSP error  

### ISSUE THREAD

**Issue by zhanghongyong123456** [ZHKKKe/MODNet#128]
When I run webcam\run.py --video is the RTSP path,Similar to the ：
cap = cv2.VideoCapture("rtsp://admin:zhy123456@192.168.3.127:554Streaming/Channels/101")
 Run about a minute, this error, directly exit the program
![image](https://user-images.githubusercontent.com/48466610/128836951-f0bb1419-f775-4365-bf57-2250dc620e7f.png)

**Comment by ZHKKKe** [comment]
@zhanghongyong123456 
Hi, thanks for your attention.
It seems an error reported by OpenCV. Sorry that I do not meet this problem before.

**Comment by ZHKKKe** [comment]
For your questions:
**Q1: do you have RTSP real-time video stream after testing，What FPS was achieved and in what configuration was it tested**
Nope. I did not try RTSP.

**Q2:  As for test speed, I got 15fps on 640x360 video and 6fps on 4K video, which is not real time（super 2060 8G），i feel like missed something，give me some advice**
It seems the model runs on CPU. Please check it.

**Q3: a difference between the local test（PC） and the demo you gave，How can I improve the results，Whether different models are used, and whether the models in demo will be open source in the future**
The first step may add more training data. Sorry that no more pre-trained models will be released in the future.
