### ISSUE TITLE
where can I get some video used in demo

### ISSUE THREAD

**Issue by hirokic5** [ZHKKKe/MODNet#129]
Thanks great repository & research !!! SOC Adaptation is very cool technique.
By the way, Are videos used in demo available ???
I would like to compare my own model to your great MODNet, but I coudln't find those videos.

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.
You can find the videos from [Pexels](https://www.pexels.com) .

**Comment by hirokic5** [comment]
Thanks for quick reply!! I understood!
