### ISSUE TITLE
关于SOC的训练问题

### ISSUE THREAD

**Issue by mmyjjl1009** [ZHKKKe/MODNet#13]
您好，关于soc的训练还有几个问题想请问一下。
在soc的时候，需要训练多少个epoch呢？
我自己在复现的时候，是按照论文中的Adam优化器 1e-4 的学习率去微调，我设置了30个epoch。但是发现在微调过程中loss在第一轮是先上升的很快，然后逐渐下降，但下降的并不多。并且在验证集上的iou还在不断下降。
我目前不知道是哪个环节出了问题，还望您指点一下。
非常感谢 ！~

**Comment by ZHKKKe** [comment]
SOC的作用是将模型适应到新的data domain。请检查以下几个方面:
1. 你使用的测试集和用于SOC的无标签数据集是否属于同一domain？如果不是，在指标上出现下降是有可能的 (因为模型泛化到了新的domain)。
2. SOC训练阶段的无标签数据有多少？SOC需要数量较大的无标记数据以防止过拟合。
3. SOC阶段需要固定BN参数。我们还将batch size设置为1。

SOC阶段需要一定的epoch进行收敛，我们在10-30epoch间的适当位置停止训练。此外，你提到的损失先上升后下降与我们的情况是一致的。但是在我们实验里，SOC训练损失会以很慢的速度不断减小。

在我们的实验中，用于SOC阶段的训练和测试数据均无标注，因此我们无法准确知道指标上的变化。但是，我们在视觉效果上观察到了极大的提升。

**Comment by mmyjjl1009** [comment]
> SOC的作用是将模型适应到新的data domain。请检查以下几个方面:
> 
> 1. 你使用的测试集和用于SOC的无标签数据集是否属于同一domain？如果不是，在指标上出现下降是有可能的 (因为模型泛化到了新的domain)。
> 2. SOC训练阶段的无标签数据有多少？SOC需要数量较大的无标记数据以防止过拟合。
> 3. SOC阶段需要固定BN参数。我们还将batch size设置为1。
> 
> SOC阶段需要一定的epoch进行收敛，我们在10-30epoch间的适当位置停止训练。此外，你提到的损失先上升后下降与我们的情况是一致的。但是在我们实验里，SOC训练损失会以很慢的速度不断减小。
> 
> 在我们的实验中，用于SOC阶段的训练和测试数据均无标注，因此我们无法准确知道指标上的变化。但是，我们在视觉效果上观察到了极大的提升。

谢谢您的回答。
我所使用的训练集和测试集是属于同一个domain的，训练集包含了700张连续视频帧。并且还会加入简单的仿射变换和反转等增强。
另外我发现在您提供的colab上，和我将代码下载到本地后，对同一批数据进行测试，测试结果很不相同。这是为什么呢？权重使用的是相同的基于Image的
colab:
![6_0000](https://user-images.githubusercontent.com/35676173/101875035-e9f97280-3bc4-11eb-9e4f-26c7cc541812.png)
![6_0001](https://user-images.githubusercontent.com/35676173/101875041-eb2a9f80-3bc4-11eb-9786-e33531bb036e.png)
![6_0002](https://user-images.githubusercontent.com/35676173/101875042-ebc33600-3bc4-11eb-981f-677086d1098b.png)
本地：
![6_0000](https://user-images.githubusercontent.com/35676173/101875071-f67dcb00-3bc4-11eb-9932-a3c7d2416d9e.png)
![6_0001](https://user-images.githubusercontent.com/35676173/101875073-f7166180-3bc4-11eb-9f97-5774e40d0d63.png)
![6_0002](https://user-images.githubusercontent.com/35676173/101875075-f7aef800-3bc4-11eb-86f3-500cd083f415.png)

**Comment by ZHKKKe** [comment]
700张的训练数据相对较小，可能会发生过拟合。在SOC阶段，我们希望无标签数据与真实数据尽可能一致，因此我们仅使用水平翻转作为数据增强。

对于本地测试的问题，请检查输入的格式是否符合要求，例如，通道排序是否为RGB,，数值是否norm到(-1, 1)，等。输入格式的不一致会对网络造成很大的影响。
