### ISSUE TITLE
你好，作者大大，训练中间过程的效果是把人像都抠没了，请问这是正常的吗？

### ISSUE THREAD

**Issue by xjiao004** [ZHKKKe/MODNet#130]

**Comment by xjiao004** [comment]
再问下，用[0,1]的label训练可以吗？

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。
我们在训练过程中没有遇到人像被抠没的问题。请尝试检查并调整你的训练超参数。
根据我的经验，使用[0, 1] label 训练应该也是可以收敛的。

**Comment by xjiao004** [comment]
嗯，感谢作者你的回复。经过检查应该是我的data loader的问题。另外想请问下你们training之前有没有做一定的pretrain呢？

**Comment by xjiao004** [comment]
你好，作者大大，还是像具体请教下像这样的中间模型结果对不对呢？
![image](https://user-images.githubusercontent.com/22072024/129132552-a52e3bd0-dc7c-4805-930c-a0905933981d.png)

**Comment by xjiao004** [comment]
用的开源模型pretrain方式训练，输入512x512,模型中间结果是这样的：
![image](https://user-images.githubusercontent.com/22072024/129133608-463a3952-aa5e-4d24-aa03-7eec96947fb3.png)
请问，以上两种情况是正常的吗？非常感谢！！！

**Comment by ZHKKKe** [comment]
你好，以上两种情况在训练早期都是有可能的，具体需要看有没有预训练和使用的网络结构。

**Comment by xjiao004** [comment]
你好，那网络是不是一般都要做预训练呢？我是train from scratch的，没做任何预训练，不好意思哈，对预训练这个一直搞不大明白。预训练是指在imagenet上训练backbone的意思吗？

**Comment by ZHKKKe** [comment]
@xjiao004 
是的，一般是用一些已有的别人训练好的模型作为初始化，然后进行训练。这样可以保证模型的收敛。

**Comment by xjiao004** [comment]
嗯，明白了，感谢感谢！！！

**Comment by xjiao004** [comment]
![image](https://user-images.githubusercontent.com/22072024/130163582-64791bb8-bbc1-4bc4-89a2-8cabef0cefd6.png)
作者大大你好，又来打搅你了，在训练过程中，测试其中间模型发现其效果不稳定，一会儿抠好了一会儿又抠没了，请问这种情况是正常的吗？我想着先训练一个baseline就没做任何的数据增强。

**Comment by imliupu** [comment]
#135 
你可以参考下我的这个 issue，我通过微调解决了大部分情况下闪烁的问题

**Comment by xjiao004** [comment]
> #135
> 你可以参考下我的这个 issue，我通过微调解决了大部分情况下闪烁的问题

你的闪烁是局部闪烁还是全局得像上面这种？我也有微调过开源模型，它得loss收敛确实会收敛到很小，现在这个模型loss还非常大，不清楚是不是因为还没收敛足够得问题导致得。

**Comment by ZHKKKe** [comment]
@xjiao004 你好，我们在训练中没有出现过这样的情况，这应该是训练没有收敛。

**Comment by fable-cuocuo** [comment]
> 嗯，感谢作者你的回复。经过检查应该是我的data loader的问题。另外想请问下你们training之前有没有做一定的pretrain呢？

你好，请问你的data loader是哪里出了问题啊？我也出现了把人像扣没了的问题

**Comment by Tanlang180** [comment]
你好，你训练时候用的是adobe image matting数据集吗

**Comment by xjiao004** [comment]
> > 嗯，感谢作者你的回复。经过检查应该是我的data loader的问题。另外想请问下你们training之前有没有做一定的pretrain呢？
> 
> 你好，请问你的data loader是哪里出了问题啊？我也出现了把人像扣没了的问题

你好，实验发现不一定是data loader的问题，有可能是模型问题哦，另外【0，1】标签是可以训练的。

**Comment by xjiao004** [comment]
> 你好，你训练时候用的是adobe image matting数据集吗

我用了Video240K数据集，需要自己合成。
