### ISSUE TITLE
README.md说模型仅有7M，为什么预训练模型都是25m多，这个7m是怎么来的？

### ISSUE THREAD

**Issue by ToBigboss** [ZHKKKe/MODNet#132]

**Comment by ZHKKKe** [comment]
你好，7m的模型是优化过的模型，没有开源。对网络结构进行了优化减少了参数，同时进行了fp16量化。

**Comment by ToBigboss** [comment]
> 你好，7m的模型是优化过的模型，没有开源。对网络结构进行了优化减少了参数，同时进行了fp16量化。

哦哦  好的，那就是说fp32的话差不多14m，modnet压缩下来对效果影响大吗，有没有一些压缩/降低计算量和size的技术路线呢？  你看商业版本效果要好很多

**Comment by ToBigboss** [comment]
> 你好，7m的模型是优化过的模型，没有开源。对网络结构进行了优化减少了参数，同时进行了fp16量化。

**Comment by ZHKKKe** [comment]
@ToBigboss 
进行fp16压缩对结果是基本没有影响的。

**Comment by ZHKKKe** [comment]
@norris9410 
Yes. The model we released on the website is trained on a larger dataset.
