### ISSUE TITLE
How to calculate the MSE and MAD ?

### ISSUE THREAD

**Issue by AmberCheng** [ZHKKKe/MODNet#134]
Hi, I have found the MSE and MAD in the paper are of the same magnitude. 

In my thought, MAD is ' np.mean(np.abs(x-y))' and MSE is 'np.mean((x-y)**2)'. 

I wonder how you calculate the evaluation metrics?

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

Yes, we calculate the metrics the same as:
MAD = np.mean(np.abs(x-y)) 
MSE = np.mean((x-y)**2)

In our case, they have the same magnitude. 
If you meet some problems, could you share more info with me?

**Comment by AmberCheng** [comment]
> Hi, thanks for your attention.
> 
> Yes, we calculate the metrics the same as:
> MAD = np.mean(np.abs(x-y))
> MSE = np.mean((x-y)**2)
> 
> In our case, they have the same magnitude.
> If you meet some problems, could you share more info with me?


I use the code below to moke  (x-y) :
`import numpy as np

x = np.random.normal(0.0000001, 0.001, size=(512, 1024))

dist_mad = np.mean(np.abs(x))
dist_mse = np.mean((x)**2)

print(dist_mad, dist_mse)`

the MAD and MSE have different magnitudes.

**Comment by ZHKKKe** [comment]
Sorry for my late response.
Please use the real error for calculation and comparison. MSE and MAE may have different magnitudes under some cases, but they may have the same maginitudes under other cases.
