### ISSUE TITLE
transforms.Compose CPU资源占用较高，如何优化？

### ISSUE THREAD

**Issue by zxbit2011** [ZHKKKe/MODNet#136]
问题：
````
im_transform = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
        ])
...
...

im = Image.fromarray(im)
im = im_transform(im)                 # cpu 占用很高
````

测试环境：
CPU：Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz     10核 20线程
并发数：10
图片大小：650kb
````
$ top
top - 17:02:30 up 3 days,  3:09,  7 users,  load average: 9.60, 3.08, 1.29
Tasks: 393 total,   5 running, 388 sleeping,   0 stopped,   0 zombie
%Cpu(s): 79.3 us,  6.4 sy,  0.0 ni, 13.9 id,  0.1 wa,  0.1 hi,  0.1 si,  0.0 st
MiB Mem :  63963.6 total,  32983.9 free,  22129.4 used,   8850.3 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  41031.4 avail Mem
````

**Comment by imliupu** [comment]
> 问题：
> 
> ```
> im_transform = transforms.Compose([
>             transforms.ToTensor(),
>             transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
>         ])
> ...
> ...
> 
> im = Image.fromarray(im)
> im = im_transform(im)                 # cpu 占用很高
> ```
> 
> 测试环境：
> CPU：Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz 10核 20线程
> 并发数：10
> 图片大小：650kb
> 
> ```
> $ top
> top - 17:02:30 up 3 days,  3:09,  7 users,  load average: 9.60, 3.08, 1.29
> Tasks: 393 total,   5 running, 388 sleeping,   0 stopped,   0 zombie
> %Cpu(s): 79.3 us,  6.4 sy,  0.0 ni, 13.9 id,  0.1 wa,  0.1 hi,  0.1 si,  0.0 st
> MiB Mem :  63963.6 total,  32983.9 free,  22129.4 used,   8850.3 buff/cache
> MiB Swap:      0.0 total,      0.0 free,      0.0 used.  41031.4 avail Mem
> ```

建议使用 cuda 进行优化，我自己的trt（c++）优化前 cpu 使用率到了40多（预测和后处理多线程并行），而且有个核跑满了，我用 cuda 把预处理和后处理都放到 gpu 上去了，现在 cpu 使用率只有 15 左右了，而且整个推理速度也快了很多

**Comment by imliupu** [comment]
> > > 问题：
> > > ```
> > > im_transform = transforms.Compose([
> > >             transforms.ToTensor(),
> > >             transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
> > >         ])
> > > ...
> > > ...
> > > 
> > > im = Image.fromarray(im)
> > > im = im_transform(im)                 # cpu 占用很高
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 测试环境：
> > > CPU：Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz 10核20线程
> > > 并发数：10
> > > 图片大小：650kb
> > > ```
> > > $ top
> > > top - 17:02:30 up 3 days,  3:09,  7 users,  load average: 9.60, 3.08, 1.29
> > > Tasks: 393 total,   5 running, 388 sleeping,   0 stopped,   0 zombie
> > > %Cpu(s): 79.3 us,  6.4 sy,  0.0 ni, 13.9 id,  0.1 wa,  0.1 hi,  0.1 si,  0.0 st
> > > MiB Mem :  63963.6 total,  32983.9 free,  22129.4 used,   8850.3 buff/cache
> > > MiB Swap:      0.0 total,      0.0 free,      0.0 used.  41031.4 avail Mem
> > > ```
> > 
> > 
> > 建议使用cuda进行优化，我自己的trt（c++）优化前cpu使用率到了40多（预测和后处理多线程跑并行），而且我用cuda优化和后处理都把把到gpu上去了，现在cpu使用率只有15左右了，而且整个推理速度也快了很多
> 
> 非常感谢你的回答，能否贴一下优化关键代码，学习一下
给你一个预处理的参考吧，其他的处理都比较简单用 cuda
`
// resize，bgr2rgb，归一化，rgb2rgb_plane(rgb2blob)，此内核实现了 cv::blobFromImage 的功能
__global__ void resize_bilinear_and_preprocess_kernel(uint8_t* src, float* out, int w, int h, int c, int w2, int h2, bool swap_rb) {
	int numberPixel = w2 * h2;
	float x_ratio = float(w) / w2;
	float y_ratio = float(h) / h2;
	int stepOut = w2 * c;
	int stepSrc = w * c;
	unsigned int threadId = blockIdx.x * threadNum * elemsPerThread + threadIdx.x * elemsPerThread;
	int shift = 0;
	while (threadId < numberPixel && shift < elemsPerThread) {
		int yy = threadId / w2;
		int xx = threadId % w2;

		float fx = (xx + 0.5) * x_ratio - 0.5;
		float fy = (yy + 0.5) * y_ratio - 0.5;

		int ix = floor(fx);
		int iy = floor(fy);

		fy -= iy;
		if (iy < 0) {
			fy = 0, iy = 0;
		}
		if (iy > w - 2) {
			fy = 0, iy = w - 2;
		}

		fx -= ix;
		if (ix < 0) {
			fx = 0, ix = 0;
		}
		if (ix > w - 2) {
			fx = 0, ix = w - 2;
		}

		short cbufx[2];
		cbufx[0] = (1.f - fx) * 2048;
		cbufx[1] = 2048 - cbufx[0];

		short cbufy[2];
		cbufy[0] = (1.f - fy) * 2048;
		cbufy[1] = 2048 - cbufy[0];

		for (int k = 0; k < c; ++k)
		{
			// 计算 resize 之后 yy * stepOut + 3 * xx + k 处的值
			float resized_value = (*(src + iy * stepSrc + 3 * ix + k) * cbufx[0] * cbufy[0] +
				*(src + (iy + 1) * stepSrc + 3 * ix + k) * cbufx[0] * cbufy[1] +
				*(src + iy * stepSrc + 3 * (ix + 1) + k) * cbufx[1] * cbufy[0] +
				*(src + (iy + 1) * stepSrc + 3 * (ix + 1) + k) * cbufx[1] * cbufy[1]) >> 22;

			int index = yy * stepOut + 3 * xx + k;

			//*(out + index) = resized_value;

			// 如果需要交换 rb 通道，如传入 bgr 时即可转为 rgb
			if (swap_rb)
			{
				// 如果不是 g 通道，则交换
				if (index % 3 != 1)
				{
					// 交换 rb 通道
					index = int(index / 3) * 3 + (index % 3 == 0 ? 2 : 0);
				}
			}

			// 归一化
			float norm_value = (resized_value - 127.5) / 127.5;

			// tensorrt 输入为 rgb plane，因此这里要 split 成 rgb 3个 plane
			int plane_size = w2 * h2;
			int plane_index = plane_size * (index % 3) + int(index / 3);
			*(out + plane_index) = norm_value;
		}
		shift++;
		threadId++;
	}
}`

**Comment by imliupu** [comment]
> > > > 问题：
> > > > ```
> > > > im_transform = transforms.Compose([
> > > >             transforms.ToTensor(),
> > > >             transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
> > > >         ])
> > > > ...
> > > > ...
> > > > 
> > > > im = Image.fromarray(im)
> > > > im = im_transform(im)                 # cpu 占用很高
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 测试环境：
> > > > CPU：Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz 10核20线程
> > > > 并发数：10
> > > > 图片大小：650kb
> > > > ```
> > > > $ top
> > > > top - 17:02:30 up 3 days,  3:09,  7 users,  load average: 9.60, 3.08, 1.29
> > > > Tasks: 393 total,   5 running, 388 sleeping,   0 stopped,   0 zombie
> > > > %Cpu(s): 79.3 us,  6.4 sy,  0.0 ni, 13.9 id,  0.1 wa,  0.1 hi,  0.1 si,  0.0 st
> > > > MiB Mem :  63963.6 total,  32983.9 free,  22129.4 used,   8850.3 buff/cache
> > > > MiB Swap:      0.0 total,      0.0 free,      0.0 used.  41031.4 avail Mem
> > > > ```
> > > 
> > > 
> > > 建议使用cuda进行优化，我自己的trt（c++）优化前cpu使用率到了40多（预测和后处理多线程跑并行），而且我用cuda优化和后处理都把把到gpu上去了，现在cpu使用率只有15左右了，而且整个推理速度也快了很多
> > 
> > 
> > 非常感谢你的回答，能否贴一下优化关键代码，学习一下
> 
> 等我后面开个仓库吧，放一下 c++版的TRT modnet，python版的 TRT 目前 windows 还不支持

你邮件我，我加你，可以给你关键代码

**Comment by zxbit2011** [comment]
> imliupu@126.com

已邮，非常感谢

**Comment by ZHKKKe** [comment]
@imliupu 
Good for you. 感谢你的解答。
