### ISSUE TITLE
Which platform/software did you use for annotating the ground truth

### ISSUE THREAD

**Issue by Saleh-Gholam-Zadeh** [ZHKKKe/MODNet#137]
Dear @ZHKKKe 

May I ask which platform/software did you use for annotating the ground truth?

In my case, I am working with some videos and I want to annotate the background segmentation map. I would be thankful if You would suggest me the best free software/platform that can be used for generating the ground truth. 

Best regards,
Saleh

**Comment by ZHKKKe** [comment]
@Saleh-Gholam-Zadeh 
Thanks for your attention.
Sorry that We used PhotoShop, which is not free.
