### ISSUE TITLE
Error: forward() missing 1 required positional argument: 'inference'

### ISSUE THREAD

**Issue by fazal-e-majid** [ZHKKKe/MODNet#138]
Beautiful work done by the developer. I'm loving it.

I tried the colab, it works fine. but when I try to `torch.jit.trace(modnet, example_input)` , it's giving me an Error
**TypeError: forward() missing 1 required positional argument: 'inference'**

i ran the code in colab, my code is:

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as transforms
from src.models.modnet import MODNet

model_path = './pretrained/modnet_photographic_portrait_matting.ckpt'

modnet = MODNet(backbone_pretrained=False)
modnet = nn.DataParallel(modnet).cuda()

modnet.load_state_dict(torch.load(model_path))
modnet.eval()

#works fine this point

example_input = torch.rand(1, 3, 256, 256) # also tried  rand(1, 3, 256, 256).cuda()
traced_model = torch.jit.trace(modnet, example_input) # Giving error at this point
```

A screenshot is attached:

<img width="1115" alt="Screenshot 2021-09-01 at 11 55 22 AM" src="https://user-images.githubusercontent.com/48935340/131625961-ad8cc992-c655-4545-94ae-94d2e1681b45.png">

I'll really appreciate your help.

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.
I hope you have addressed the problem.
If any question, free to pin me.
