### ISSUE TITLE
How to get the alpha video

### ISSUE THREAD

**Issue by mayingwuhu** [ZHKKKe/MODNet#139]
python -m demo.video_matting.custom.run --video 
I can run demo.video_matting.custom.run.py.But I want to get the alpha video , can you tell me how to get it?

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention. 
I hope you have address the problem.

**Comment by italosalgado14** [comment]
@mayingwuhu Hi! How did you get the alpha matte for a full video? I appreciate the answer.
