### ISSUE TITLE
error occured when run on windows cpu

### ISSUE THREAD

**Issue by zhangyunming** [ZHKKKe/MODNet#14]
hi, because there is no GPU on my windows pc, so i change the GPU to cpu by :

![企业微信截图_16076615348073](https://user-images.githubusercontent.com/12590457/101862723-e60e2600-3bad-11eb-8302-a808f67aedb2.png)
and chang the code in image_matting/inference.py line 98:
 _, _, matte = modnet(im.cpu(), inference=False) 

but error occured as:
![企业微信截图_16076616854716](https://user-images.githubusercontent.com/12590457/101862957-34232980-3bae-11eb-8da8-bd2032bdbbf1.png)

my torch-cpu=1.6.0
thanks.

**Comment by ZHKKKe** [comment]
Hi. Thanks for your attention. 

Our pre-trained models are wrapped by nn.DataParallel. For your problem, you may need to load the ckpt file by using:

```
model.load_state_dict(torch.load(args.ckpt_path, map_location=torch.device('cpu'))['module'])
```

Thank you for pointing it out. We will soon improve the code to make it compatible with cpu.

**Comment by zhangyunming** [comment]
###for cpu
    modnet = MODNet(backbone_pretrained=False)
    modnet = nn.DataParallel(modnet)
    modnet.load_state_dict(torch.load(args.ckpt_path,map_location=torch.device('cpu')))
    modnet.eval()

    just ok above.  i delete  modnet = nn.DataParallel(modnet).
    thanks

**Comment by ZHKKKe** [comment]
Yes. This is another solution. Good job :)
