### ISSUE TITLE
onnx 推理比 ckpt 慢？

### ISSUE THREAD

**Issue by wangjing60755** [ZHKKKe/MODNet#141]
在gpu 上推理，ckpt约30ms, onnx 要350ms? why??
cpu上，onnx确实比ckpt快一些。
很疑惑！

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。
请问使用ONNX版本时是否执行多次推理？ ONNX模型在Session加载后第一次推理时会执行一些初始化操作，可能会极大地影响推理速度。可能可以使用for循环测试下后续速度。
