### ISSUE TITLE
Why not train branch S first?

### ISSUE THREAD

**Issue by syfbme** [ZHKKKe/MODNet#147]
branch D and branch F depend on the result of branch S while branch S is independent. What if we train branch S first and get a better result to pass to branch D and branch F?
Will the result be better or speed up the train? I wonder if it is worth a try...

**Comment by ZHKKKe** [comment]
Thanks for your attention.
If we train S together with other branches, we can train the whole network end-to-end, which is faster. Besides, training all branches together achieved better performance in my experiments as the features are optimized in parallel.

**Comment by syfbme** [comment]
Thanks for your reply. That makes sense. Close it.
