### ISSUE TITLE
Any Updates on License

### ISSUE THREAD

**Issue by kaswani29** [ZHKKKe/MODNet#154]
Will you be updating the license soon?

**Comment by ZHKKKe** [comment]
A good news. The license will be updated soon!

**Comment by gsrujana** [comment]
Is there a plan to share the 3K annotated images as well?

**Comment by Stplceo** [comment]
> A good news. The license will be updated soon!

This is great ,  the models being used in colab demo will be available for public use after the licence update ?
Also if you have a specific time on license update

**Comment by ZHKKKe** [comment]
@Stplceo 
Yes. The models used in the colab demos will be available under the Apache license.
The update time will be these few weeks. I am busy these days, so the update is delayed.

**Comment by ZHKKKe** [comment]
@gsrujana 
Sorry that the dataset will not be open-source at this time. 
However, we have plans to release a training dataset several months later. Please follow https://github.com/ZHKKKe/PPM for latest information if  necessary.

**Comment by ZHKKKe** [comment]
Hi, all. 
Our paper is accepted by AAAI 2022. The license of our github project has been changed to the Apache License 2.0 license.
I would be happy if you could share your APP based on MODNet with me.
