### ISSUE TITLE
difference between the video Inference and single Image Inference in the code

### ISSUE THREAD

**Issue by miaoYuanyuan** [ZHKKKe/MODNet#16]
Hi , Thanks for your great work !
I am confused . what the difference between the video inference and the single image inference? except that where the picture came from.  and the difference between the two ckpt file: modnet_webcam_portrait_matting.ckpt, modener_photographic_portrait_matting.ckpt. Thank you!

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention. 

The main implementation of  the video inference and the single image inference are the same. We just provide two demos for different users.
The two ckpt files are different: 
1. `modener_photographic_portrait_matting.ckpt` is the model trained on our labeled dataset only.
2. `modnet_webcam_portrait_matting.ckpt` is the model trained on our labeled dataset and finetuned in the real-world unlabeled video data by using SOC.

**Comment by miaoYuanyuan** [comment]
It is useful, Thank you very much!
