### ISSUE TITLE
HOW TO CALCULATE SEMANTIC SCALE,MATTE SCALE AND DETAIL SCALE 

### ISSUE THREAD

**Issue by vprashrex** [ZHKKKe/MODNet#168]
L = λs Ls + λd Ld + λα Lα

you said .. you have to adjust according to your dataset  
is there any way to adjust this scale 

THANK YOU !

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.
It is easy to set. You can just use λs=1, λd=1, λα=1.  In our cases, we use λs=10, λd=10, λα=1.

**Comment by vprashrex** [comment]
OK THANKS FOR YOUR REPLY ! ... GREAT WORK
