### ISSUE TITLE
The difference between using BN or using IBNorm

### ISSUE THREAD

**Issue by lxy2017** [ZHKKKe/MODNet#17]
Hi, I noticed that you use IBNorm in your code( combine IN and BN into one layer). What are the benefits of task?  Thanks！

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

Our experiments show that IBNorm can bring a better performance in this task, so we use it.

**Comment by lxy2017** [comment]
> Hi, thanks for your attention.
> 
> Our experiments show that IBNorm can bring a better performance in this task, so we use it.

Thank you for your answer.  Anything to explain this phenomenon?  Which tasks can I use IBNorm?

**Comment by ZHKKKe** [comment]
I know that IBNorm can improve the results when batch size is relatively small, *e.g.*, batch size = 16 used in our methods.
Maybe you can learn more from the paper that proposes IBNorm: https://arxiv.org/abs/1807.09441
