### ISSUE TITLE
Online Application doesn't work: Network error

### ISSUE THREAD

**Issue by lxxue** [ZHKKKe/MODNet#182]
Thanks for the great work!

I tried the demo on the website but it is not working. After uploading the image it says "Network error". Could you take a look at it? Thanks in advance.

**Comment by ZHKKKe** [comment]
I just find this problem. 
I will address this soon. You may also try [this link](https://zhke.io/#/?modnet_demo).

**Comment by lxxue** [comment]
Thanks!

**Comment by ZHKKKe** [comment]
The problem is fixed.
