### ISSUE TITLE
mobilenetv2_human_seg.ckpt，这个文件是该项目中的吗？

### ISSUE THREAD

**Issue by juzuo** [ZHKKKe/MODNet#20]
作者你好，
我刚才试了试开源的模型，发现头发抠的非常精细，但是其它地方比较容易多抠出一些东西，特别是背景略复杂的时候。请问加上人体segmentation会不会好些？正好我在你分享的google drive链接中看到这个：mobilenetv2_human_seg.ckpt。请问是做这件事的吗？请问mobilenetv2_human_seg.ckpt怎么使用呢？

谢谢！

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。

是的，正如我们在image matting demo里介绍的，我们的训练集只包含3000个前景，因此模型在复杂背景下依然会输出错误的人像语义信息 (准确的语义信息是需要大量数据来学习的)。
mobilenetv2_human_seg.ckpt 这个模型是MODNet中Low-Resolution分支使用的预训练模型，在我们发布训练代码的时候会用到。它来自[这个Git仓库](https://github.com/thuyngch/Human-Segmentation-PyTorch)。 该模型在背景复杂的情况下也会出现人像语义信息预测的错误。

**Comment by juzuo** [comment]
明白了。great work!!

**Comment by zhanghongyong123456** [comment]
> 
请教几个问题，
1.假如我想训练其他物体而非人，我该如何设置低分辨率的预训练模型呢，是否需要将mobilenetv2_human_seg.ckpt替换成一般性的预训练模型，能否提供个地址
2.如果换成一般性的预训练模型，对分割影响有多大，会不会分割不出来，还是说只要数据量大就可以自动实现好的分割
期待您的回复。
