### ISSUE TITLE
How to synthesize a new background?

### ISSUE THREAD

**Issue by LingQiu** [ZHKKKe/MODNet#27]
How to synthesize a new background?

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

I use our [Image Matting Colab Demo](https://colab.research.google.com/drive/1GANpbKT06aEFiW-Ssx0DQnnEADcXwQG6?usp=sharing#scrollTo=JOmYOHKfgQ5Y) as an example.
In **Section 4 - Visualization**, you can find this line:
```
foreground = image * matte + np.full(image.shape, 255) * (1 - matte)
```
This is the formula for compositing a white background. You just need to replace `np.full(image.shape, 255)` by your background image (you can load the background image and send it to the function `conbined_display`).

**Comment by LingQiu** [comment]
Thanks for quick response.It is useful.
