### ISSUE TITLE
run webcam demo failed

### ISSUE THREAD

**Issue by hclakk** [ZHKKKe/MODNet#28]
Hi,

I'm trying to run the video matting demo based on WebCam, after follow your recommend cmd.
It failed at pytorch issue,but I google and can't find other error issue like this.
My environment is ubuntu 16.04 with gpu rtx2070 python3.6 cuda10 
  [
![1186486](https://user-images.githubusercontent.com/43768387/102461934-2412ba80-4084-11eb-85d2-6bc4e544c203.png)
](url)

Could you help me solve this error.
Thanks

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

Oh... It is a bug of PyTorch. Please change `inferece=True` to `True`, *i.e.*, delete `inference=`. I will modify the code.

**Comment by hclakk** [comment]
Thanks for quick reply.
It works like a charm.
