### ISSUE TITLE
有百度云的地址吗？

### ISSUE THREAD

**Issue by HINATASDK** [ZHKKKe/MODNet#31]
预训练模型的GD地址由于现在较难科学上网，无法打开，希望可以更新到度盘或者直接放在github上

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。

请在访问以下链接下载预训练模型 
链接：https://pan.baidu.com/s/1qj6An3FEFaWGOsCg0Ysg-w 
提取码：8hzc

**Comment by HINATASDK** [comment]
🤝🤝
