### ISSUE TITLE
Support for Python 3.8?

### ISSUE THREAD

**Issue by jacksongoode** [ZHKKKe/MODNet#32]
I think the version of torch your using (1.0.0)  requires Python 3.6. However, since most people are on 3.8 now, would it be possible to update the script to use a later version of torch?

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

Have you tried to use a higher version of PyTorch? I think the current code will be compatible with PyTorch >= 1.0.0.
My current machine can't update the NVIDIA driver, so I can't install the corresponding CUDA to support the higher version of PyTorch. I will try to solve this problem if possible.

**Comment by jacksongoode** [comment]
Yes, you're right! I tried other versions of torch and just didn't try the latest one. It works if you remove the restriction to version 1.0.0 from torch.

**Comment by ZHKKKe** [comment]
@jacksongoode 
Thanks for your suggestions! 
I will remove it tomorrow.
