### ISSUE TITLE
No module named ‘src.models’

### ISSUE THREAD

**Issue by AugustLee93** [ZHKKKe/MODNet#34]
when I tred to complie image_matting, here is the error that I got. Does anyone know how to fix it ? I am kinda new for programming. Thx.

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention!

Our code is organized as a python package. Therefore, please switch to the root path of the project, and run:
```
python -m demo.image_matting.colab.inference
```

BTW,  `demo/image_matting/colab/inference.py` is the inference code for our Colab demo. If you want to run it from the terminal, you may need to make some necessary changes.

**Comment by AugustLee93** [comment]
> Hi, thanks for your attention!
> 
> Our code is organized as a python package. Therefore, please switch to the root path of the project, and run:
> 
> ```
> python -m demo.image_matting.colab.inference
> ```
> 
> BTW, `demo/image_matting/colab/inference.py` is the inference code for our Colab demo. If you want to run it from the terminal, you may need to make some necessary changes.

THX, that helps!
