### ISSUE TITLE
recommended preprocessing for video model

### ISSUE THREAD

**Issue by eyaler** [ZHKKKe/MODNet#40]
for the pretrained webcam/custom video model, is it recommended to always resize to 672x512 ? or can i use the same preprocessing as for the photographic model (https://github.com/ZHKKKe/MODNet/blob/master/demo/image_matting/colab/inference.py)? for example, if my video is 16/9 instead of 4/3, or god forbid, vertical video, would it be better to use the latter preprocessing that would more closely preserve the aspect ratio?

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

**Q1: for the pretrained webcam/custom video model, is it recommended to always resize to 672x512 ?**
Nope. I think the original video ratio should be used. Sorry that We forgot this point before. 
We will work on this and update the demo in these two days.

**Comment by ZHKKKe** [comment]
@eyaler The bug is fixed. Thanks,

**Comment by eyaler** [comment]
there is still some difference from https://github.com/ZHKKKe/MODNet/blob/master/demo/image_matting/colab/inference.py where the logic is applied only when `if max(im_h, im_w) < ref_size or min(im_h, im_w) > ref_size`. is that more appropriate for the photographic model but not for the video model?

**Comment by ZHKKKe** [comment]
Nope. I found that the effect of the conditional statement `if max(im_h, im_w) < ref_size or min(im_h, im_w) > ref_size` on the result is negligible. Therefore, I did not add it in the video demo.
