### ISSUE TITLE
Modnet Demo App not working

### ISSUE THREAD

**Issue by Lion471** [ZHKKKe/MODNet#41]
The Gradio demo app you created does not appear to be working. It says "Launching Your Gradio Interface". "You will receive an email notification when the process is complete. You may close this page."

I don't know what this means. It also wasn't saying this yesterday.

https://gradio.app/g/modnet

**Comment by aliabd** [comment]
@Lion471 Sorry about that. The link is back up. We've also recently migrated to more stable infrastructure - so this shouldn't happen again.
