### ISSUE TITLE
关于mobilenetv2_human_seg.ckpt一些问题

### ISSUE THREAD

**Issue by lblbk** [ZHKKKe/MODNet#42]
感谢作者论文
想问一下，上面提到的预训练权重文件我并没有在[Human-Segmentation-PyTorch](https://github.com/thuyngch/Human-Segmentation-PyTorch)找到，是UNet_MobileNetV2么，还是其他的，谢谢

**Comment by ZHKKKe** [comment]
你好。是的，网盘中的预训练权重是我们从UNet_MobileNetV2中提取的。

**Comment by lblbk** [comment]
当我去加载UNet_MobileNetV2预训练权重的时候会报一个错误

> Traceback (most recent call last):
  File "F:/MODNet/main/main.py", line 105, in <module>
    main(path)
  File "F:/MODNet/main/main.py", line 52, in main
    net = MODNet(backbone_pretrained=True)
  File "F:\MODNet\src\models\modnet.py", line 229, in __init__
    self.backbone.load_pretrained_ckpt()                
  File "F:\MODNet\src\models\backbones\wrapper.py", line 60, in load_pretrained_ckpt
    ckpt = torch.load(ckpt_path)
  File "F:\MODNet\venv\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "F:\MODNet\venv\lib\site-packages\torch\serialization.py", line 774, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'utils.logger'

当我不加载预训练权重的时候并不会遇到 请问这是我源码的问题么 还是模型的问题 谢谢

**Comment by ZHKKKe** [comment]
这里的问题是`ModuleNotFoundError: No module named 'utils.logger'`，意思是访问不到utils.logger.

你可以选择去掉文件中所有`utils.logger`相关的代码，或是在项目根目录中以包的形式访问代码（例如，`python -m folder.subfolder.file`）。请参考`demo/video_matting/webcam/README.md`.

**Comment by lblbk** [comment]
抱歉 ，我可能没有描述清楚。

当我不加载`UNet_MobileNetV2`网络预训练权重的时候，我的模型可以正常使用并且训练。

当我加载`UNet_MobileNetV2`模型的时候会报出这个错误，而且根据错误信息来看，不是我所写的代码问题，而是从您提供的网络模型代码中报出的，因为我只是实例化了`MODNet`，预加载模型权重的代码在您提供的代码有写。

我切换了torch版本跟`UNet_MobileNetV2`所用版本一样为1.2.0，还是报出这个错误。

我仔细查看了一下，并不是因为我写的代码造成的，我怀疑是不是`UNet_MobileNetV2`权重有问题。

谢谢

**Comment by ZHKKKe** [comment]
你是使用我们提供的模型还是他们repo里提供的？
我们的代码无法加载他们repo中提供的模型，因为我们对他们发布的预训练模型做了些处理。

**Comment by lblbk** [comment]
抱歉啦，我一直以为您没有提供，直到朋友提醒我，真是麻烦啦。
问题我先关啦，谢谢啦。
