### ISSUE TITLE
question on your code

### ISSUE THREAD

**Issue by zhanghui75** [ZHKKKe/MODNet#43]
https://github.com/ZHKKKe/MODNet/blob/bece9b41afd6b4c857a114e93f93a058fe32d589/src/models/modnet.py#L27
the original code is "in_x = self.inorm(x[:, self.inorm_channels:, ...].contiguous())"

Should this line use "self.bnorm_channels" instead of inorm_channels?

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

Yep... This code will cause a bug if the `in_channels` is an odd number... 
Thanks for for pointing out, and I have fixed it.
This bug will not affect the existing pretrained models since we always set `in_channels` to an even number.
