### ISSUE TITLE
train

### ISSUE THREAD

**Issue by luoww1992** [ZHKKKe/MODNet#44]
when will you share the train code, i am too eager to try it !

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.
We plan to release the main training code in this month.  :)

**Comment by 15122901359** [comment]
@ZHKKKe Hello, can  provided the training codes in this month？I'm so anxious to have a try.

**Comment by ZHKKKe** [comment]
@15122901359 The main training code is coming in these two days.

**Comment by luoww1992** [comment]
waiting......

**Comment by rose-jinyang** [comment]
Hi @ZHKKKe 
Thanks for contributing to this project.
All of us are waiting for the training code for this project.

**Comment by 972461099** [comment]
waiting......

**Comment by 15122901359** [comment]
> @15122901359 The main training code is coming in these two days.
Looking forward, thank you very much for providing the code！

**Comment by luoww1992** [comment]
> Hi, thanks for your attention.
> We plan to release the main training code in this month. :)
waiting......
.....
finished !

very good !!!
thanks !!!

**Comment by ZHKKKe** [comment]
Hi, all, 
Our main training code is available now!

**Comment by luoww1992** [comment]
https://github.com/ZHKKKe/MODNet/issues/57#issuecomment-770171312

help...
----- 原始邮件 -----
发件人：Zhanghan Ke <notifications@github.com>
收件人：ZHKKKe/MODNet <MODNet@noreply.github.com>
抄送人：luoww1992 <luoww1992@sina.com>,  Author <author@noreply.github.com>
主题：Re: [ZHKKKe/MODNet] train (#44)
日期：2021年01月28日 17点10分


Closed #44.

&mdash;
