### ISSUE TITLE
train on rgb or bgr?

### ISSUE THREAD

**Issue by ilyaskhanbey** [ZHKKKe/MODNet#45]
Hello , for image matting the train was done using bgr or rgb format?
i got better result when testing images with Bgr format (opencv format)
But when i checked your code of inference it's  seems you're using RGB (Pil format)
so i'm confused maybe in training you sed RGB format.
thks

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

We use RGB format for both training and validation. 
We also tried to train the model on RGB format and validate it on BGR format, but we got bad results.
Could you share some of your RGB and BGR results with me?
