### ISSUE TITLE
Speed Related Issue

### ISSUE THREAD

**Issue by jayesh616** [ZHKKKe/MODNet#47]
Hi,
Thank you for this great work. I really appreciate the accuracy. I wanted to segment this object at 30 FPS but relatively the detection speed is very slow. is there any way to use this as a real-time application. ?  This repo will rock in the future...!

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

Have you tried our [local WebCam demo](https://github.com/ZHKKKe/MODNet/tree/master/demo/video_matting/webcam)? In our enviroments, it can run at 20+FPS under a laptop CPU. And you should get higher FPS under a Nvidia GPU.

**Comment by jayesh616** [comment]
Thank you for the quick reply..! Yes, I tried this approach. I am getting very slow results on my CPU. I would like to use this for a real-time environment also waiting for a training guide.

**Comment by ZHKKKe** [comment]
Some other guys also reported the same problem under CPU before, but it is a rare case. 
I am sorry that I do not have any idea about how to address it since I cannot reproduce this problem. Could you try another device?

**Comment by jayesh616** [comment]
Sure....!  I will try this on the different devive and inform you of the stats and conditions if I am able to reproduce it. Thank You..!
