### ISSUE TITLE
 关于compositional loss

### ISSUE THREAD

**Issue by LianShuaiLong** [ZHKKKe/MODNet#49]
您好，有个问题想请教一下
关于 compositional loss，您论文中说到：It measures the absolute difference between the input image I and the composited image obtained from αp, the ground truth foreground, and the ground truth background.
这里的ground truth foreground， ground truth background指的是什么呢？您是在求解loss的时候用到了trimap么？
刚入门matting的小白，可能问题有点多

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。
 `compositional loss`中的`ground truth foreground`和`ground truth background`是输入图像的前景和背景。求解时候没用用到trimap。

这个loss是论文 **Deep Image Matting** 提出的，你可以参考他们原文如何计算该损失。

**Comment by LianShuaiLong** [comment]
> 你好，感谢你的关注。
> `compositional loss`中的`ground truth foreground`和`ground truth background`是输入图像的前景和背景。求解时候没用用到trimap。
> 
> 这个loss是论文 **Deep Image Matting** 提出的，你可以参考他们原文如何计算该损失。

好的，期待前辈的训练代码
