### ISSUE TITLE
TypeError: VideoWriter() missing required argument 'frameSize' (pos 5)

### ISSUE THREAD

**Issue by LianShuaiLong** [ZHKKKe/MODNet#51]
想问一下前辈，您的opencv用的是什么版本的？我用opencv创建视频流对象的时候总是报错
video_writer = cv2.VideoWriter(result,fourcc,fps,(frame_width,frame_height))

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。

请问你的问题解决了吗？我是用的是Python 3 + OpenCV 4.4.0.

**Comment by LianShuaiLong** [comment]
> 你好，感谢你的关注。
> 
> 请问你的问题解决了吗？我是用的是Python 3 + OpenCV 4.4.0.

已经解决了，是
frame_num = (Cap.get(cv2.CAP_PROP_FRAME_COUNT))
frame_width = (Cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = (Cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
返回值都是浮点数，把frame_width，frame_height 改成int就不报错了，应该不是版本的问题，
不过有个问题想问一下前辈，我用您demo里面的gif测了一下video matting，效果不怎么理想，我一会把测试结果贴到这里，您帮忙分析一下是什么原因可以嘛？

**Comment by LianShuaiLong** [comment]
![image](https://github.com/LianShuaiLong/CV_Applications/blob/master/matting/video_results/demo.gif)

**Comment by LianShuaiLong** [comment]
![image](https://github.com/LianShuaiLong/CV_Applications/blob/master/matting/video_results/demo_res.gif)

上面是我测试的结果，当时为了测试video matting,我用的录屏软件把原来的gif录成视频后做的测试，不知道这样操作会有什么不合理的地方

**Comment by ZHKKKe** [comment]
转成gif会对原始视频的质量进行很大的压缩，导致输入质量过低，所以会出现不好的效果。
你可以尝试一些其他质量较高的视频，当然，背景太复杂时依旧无法处理。
你可以尝试我们的webcam demo 来从摄像头输入中获得结果。

**Comment by LianShuaiLong** [comment]
> 转成gif会对原始视频的质量进行很大的压缩，导致输入质量过低，所以会出现不好的效果。
> 你可以尝试一些其他质量较高的视频，当然，背景太复杂时依旧无法处理。
> 你可以尝试我们的webcam demo 来从摄像头输入中获得结果。

我好像没有表达清楚我的做法：我看您给的demo里面有一个gif，我用录屏软件把那个gif录成了视频的形式(A)，然后做的video matting得到matting后的结果(B)；我给您提供的gif是将B转成了gif格式(C)贴上来的，B和C的视觉效果是一模一样的

**Comment by ZHKKKe** [comment]
你好。我指的是，我们在制作demo中gif时，图像就已经被严重压缩过了。因此，即使将它转成其他格式做matting的输入，质量依旧不足，会影响结果。

**Comment by LianShuaiLong** [comment]
> 你好。我指的是，我们在制作demo中gif时，图像就已经被严重压缩过了。因此，即使将它转成其他格式做matting的输入，质量依旧不足，会影响结果。

好的，我用高质量视频测试一下

**Comment by ZHKKKe** [comment]
我们提供的模型主要是采用WebCam采集的视频（质量并不会很高）进行的adaptation。 所以使用WebCam Demo才能得到最佳效果。Custom Video Demo是因为比较多人希望尝试，我们提供的附加Demo。
