### ISSUE TITLE
关于 adobe 数据训练的问题

### ISSUE THREAD

**Issue by albertyou2** [ZHKKKe/MODNet#52]
@ZHKKKe 
您好
我认为这是一个非常牛逼的项目！
当然，在有时候，一些特殊的图抠的不太理想，但是在正常的图抠的非常精细。
很自然的，我想到了使用更好的数据训练，比如 Adobe Deep Image Matting Dataset 数据集 
能否分享一下详细的训练过程，非常感谢！

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。
我们的训练代码预计在近期公布。请持续关注这个git仓库以获得最新消息。

**Comment by albertyou2** [comment]
感谢！我会持续关注！
