### ISSUE TITLE
Incorrect cut when camera is moving towards an object

### ISSUE THREAD

**Issue by rabbi7** [ZHKKKe/MODNet#54]
Background is cut incorrectly when camera is moving towards an object
Example video
https://www.pexels.com/ru-ru/video/4443815/

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

I will check it and give you a feedback soon.

**Comment by ZHKKKe** [comment]
Sorry for missing this question before. 
We found that our open-source model works bad if the portrait is too close to the camera, i.e., the face fulls almost the whole image. We addressed this problem in our model newly released on [this website](https://sight-x.cn/portrait_matting/).
