### ISSUE TITLE
accessible colab for video backgorund replacement with comparison to u2net

### ISSUE THREAD

**Issue by eyaler** [ZHKKKe/MODNet#55]
thanks for this amazing work and models. I have created an accessible colab allowing to replace the background of an image or video with another image or video and apply various effects including bokeh and portrait sketching.

colab: [j.mp/vid2green.](https://j.mp/vid2green)

examples: https://www.youtube.com/playlist?list=PLZV8sKAO3LzZwHGWbmRxLuQQq2lXZsBaN

examples of comparison of MODNet models and U2Net: https://twitter.com/eyaler/status/1342853216409681920

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention!

It is a cool demo! I will add the link to our repo in next update.

**Comment by ZHKKKe** [comment]
Hi, I have referred your cool demo in our README file!
