### ISSUE TITLE
trimap

### ISSUE THREAD

**Issue by lblbk** [ZHKKKe/MODNet#58]

**Comment by ZHKKKe** [comment]
你好，是的。trimap是可以从ground truth 中生成的。下面是示例代码：

```
from scipy.ndimage import grey_dilation, grey_erosion

# matte is normalized to [0, 1] 
matte = $GROUND TRUTH ALPHA MATTE$

trimap = (matte >= 0.9).astype('float32')
not_bg = (matte > 0).astype('float32')

d_size = $INPUT_IMAGE_SIZE$ // 256 * 15
e_size = $INPUT_IMAGE_SIZE$ // 256 * 15

trimap[np.where((grey_dilation(not_bg, size=(d_size, d_size))
    - grey_erosion(trimap, size=(e_size, e_size))) != 0)] = 0.5
```

**Comment by LianShuaiLong** [comment]
> 你好，是的。trimap是可以从ground truth 中生成的。下面是示例代码：
> 
> ```
> from scipy.ndimage import grey_dilation, grey_erosion
> 
> # matte is normalized to [0, 1] 
> matte = $GROUND TRUTH ALPHA MATTE$
> 
> trimap = (matte >= 0.9).astype('float32')
> not_bg = (matte > 0).astype('float32')
> 
> d_size = $INPUT_IMAGE_SIZE$ // 256 * 15
> e_size = $INPUT_IMAGE_SIZE$ // 256 * 15
> 
> trimap[np.where((grey_dilation(not_bg, size=(d_size, d_size))
>     - grey_erosion(trimap, size=(e_size, e_size))) != 0)] = 0.5
> ```

请教一下，我用了这部分代码去做trimap，但是报错了：
  trimap = (gt_matte >= 0.9).float()
  not_bg = (gt_matte > 0).float()
  d_size = image.size()[2] // 256 * 15
  e_size = image.size()[2] // 256 * 15
  trimap[np.where((grey_dilation(not_bg, size=(d_size, d_size))-grey_erosion(trimap, size=(e_size, e_size))) != 0)] = 0.5

  # calculate the boundary mask from the trimap
  boundaries = (trimap < 0.5) + (trimap > 0.5)

报错：

Traceback (most recent call last):
  File "/workspace/run.py", line 69, in <module>
    train(opt)
  File "/workspace/run.py", line 57, in train
    semantic_loss,_ ,_ = supervised_training_iter(modnet, optimizer, image, gt_matte,pretrain=True)
  File "/workspace/trainer.py", line 60, in supervised_training_iter
    trimap[np.where((grey_dilation(not_bg, size=(d_size, d_size))-grey_erosion(trimap, size=(e_size, e_size))) != 0)] = 0.5
  File "/opt/conda/lib/python3.7/site-packages/scipy/ndimage/morphology.py", line 1365, in grey_dilation
    sz = size[ii]
IndexError: tuple index out of range

我查了一下，grey_dilation的input应该是一个二维的，我这里输入的是四维的BCHW,请问有什么解决办法么？

**Comment by ZHKKKe** [comment]
@LianShuaiLong 在dataloader中读取每个样本时，从单通道的ground truth生成trimap即可。
