### ISSUE TITLE
Why my detail_loss is always 0?

### ISSUE THREAD

**Issue by smallcube** [ZHKKKe/MODNet#59]
I am training the MODNet on Adobe Matting dataset. However, my detail_loss is always 0.

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

Please check the pixel values in the loaded trimap. You need to normalize its value to `[0, 1]`.

**Comment by smallcube** [comment]
> Hi, thanks for your attention.
> 
> Please check the pixel values in the loaded trimap. You need to normalize its pixel values to `[0, 1]`.

Thanks for the reply. The problem has been solved. It turns out that in your official training code, you use "boundaries = (trimap < 0.5) + (trimap > 0.5)" to identify the transition region. I change the code to "boundaries = (trimap < 0.5) + (trimap > 0.5)".
