### ISSUE TITLE
Please add onnx export

### ISSUE THREAD

**Issue by onexuan** [ZHKKKe/MODNet#64]
Please add onnx export

**Comment by manthan3C273** [comment]
Checkout [this](https://github.com/manthan3C273/MODNet/tree/master/demo/image_matting/Inference_with_ONNX)

**Comment by onexuan** [comment]
> Checkout [this](https://github.com/manthan3C273/MODNet/tree/master/demo/image_matting/Inference_with_ONNX)

Thank you very mush for your great work. I have successfully exported with your python code. 

@manthan3C273 
Could you help me export onnx this project https://github.com/KikimorMay/MultiFace

**Comment by manthan3C273** [comment]
Okay, I'll try.

**Comment by onexuan** [comment]
> Okay, I'll try.

Thanks a lot

**Comment by ZHKKKe** [comment]
@onexuan 
The ONNX version is integrated into the master branch.
