### ISSUE TITLE
Clarification on MobileNetV2 pre-trained weights

### ISSUE THREAD

**Issue by FraPochetti** [ZHKKKe/MODNet#67]
Hi, first of all, great work here!
Incredible results, as far as I can see!

I have a quick question about the pre-trained weights you are using for MobileNetV2.
Am I correct that you are getting them from [here](https://github.com/thuyngch/Human-Segmentation-PyTorch#benchmark)?
Specifically from `UNet_MobileNetV2`?
![image](https://user-images.githubusercontent.com/1206519/108392636-3390ba00-7213-11eb-8c45-0e19691c69b0.png)

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.
Yep. You are correct.

**Comment by FraPochetti** [comment]
Thanks for the prompt reply.
I am asking because, after downloading the MobileNetV2 weights and placing them in the right folder, when instantiating the model (`model = MODNet()`), I get the following error:
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-2a44378dc05e> in <module>
----> 1 model = MODNet()

~/notebooks/francesco_nbs/modnet/MODNet/src/models/modnet.py in __init__(self, in_channels, hr_channels, backbone_arch, backbone_pretrained)
    227 
    228         if self.backbone_pretrained:
--> 229             self.backbone.load_pretrained_ckpt()
    230 
    231     def forward(self, img, inference):

~/notebooks/francesco_nbs/modnet/MODNet/src/models/backbones/wrapper.py in load_pretrained_ckpt(self)
     57             exit()
     58 
---> 59         ckpt = torch.load(ckpt_path)
     60         self.model.load_state_dict(ckpt)

/anaconda/envs/fra_modnet/lib/python3.8/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    593                     return torch.jit.load(opened_file)
    594                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 595         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    596 
    597 

/anaconda/envs/fra_modnet/lib/python3.8/site-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    772     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    773     unpickler.persistent_load = persistent_load
--> 774     result = unpickler.load()
    775 
    776     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

ModuleNotFoundError: No module named 'utils'
```

This seems to be related to potential inconsistencies between the weights were saved and how they are being loaded back.
For reference, I am using 
```
python=3.8.5
torch=1.7.1+cu101
torchvision=0.8.2+cu101
```
Have you encountered anything like that?
Maybe the pre-trained weights have been updated after you used them for your project?
Or are you using an older version of `torch`?

Once again, thanks a lot for the help!

**Comment by FraPochetti** [comment]
Ah, now I realize that the weights are located [here](https://github.com/ZHKKKe/MODNet/tree/master/pretrained).
If I use the `mobilenetv2_human_seg.ckpt` from Drive, I can load the model correctly.
Are those weights covered by the [Creative Commons Attribution NonCommercial ShareAlike 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode) as well?

**Comment by ZHKKKe** [comment]
@FraPochetti 
Hi. The original `UNet_MobileNetV2` model is wrapped by the author, so you cannot load it directly. 
The model provided in our Google Drive is the same as the original `UNet_MobileNetV2` (we just removed the wrapper to make it easier to use). 
The model `mobilenetv2_human_seg.ckpt` is not covered by the Creative Commons Attribution NonCommercial ShareAlike 4.0 license. Please use it according to [its original Repo](https://github.com/thuyngch/Human-Segmentation-PyTorch).

**Comment by FraPochetti** [comment]
Thanks a lot.
Really helpful.
