### ISSUE TITLE
哪里可以下载到“pre-trained MODNet”？

### ISSUE THREAD

**Issue by zerrojs** [ZHKKKe/MODNet#7]
多谢分享，在学习过程中，发现还没有提供pre-trained MODNet文件，这个在哪里可以下载，或者什么时候可以提供？多谢

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。

我们预计在明天发布演示程序与预训练模型。

**Comment by leemengxing** [comment]
great job！

**Comment by zerrojs** [comment]
👍，期待

**Comment by ZHKKKe** [comment]
我们的预训练模型与demo已经发布 :)
