### ISSUE TITLE
runtime error in training on single image

### ISSUE THREAD

**Issue by Randheerkumar** [ZHKKKe/MODNet#75]
**getting this:**
RuntimeError: Sizes of tensors must match except in dimension 2. Got 87 and 88 (The offending index is 0)

**code is:**
import numpy as np
from src.models.modnet import MODNet
from src.trainer import supervised_training_iter
import torchvision.transforms.functional as TF

import cv2

bs = 1         # batch size
lr = 0.01       # learn rate
epochs = 40     # total epochs

modnet = torch.nn.DataParallel(MODNet()).cuda()
optimizer = torch.optim.SGD(modnet.parameters(), lr=lr, momentum=0.9)
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=int(0.25 * epochs), gamma=0.1)

image=Image.open("image/2.jpg")  #input image
trimap=Image.open("trimap/trimap.png") # trimap
gt_matte=Image.open("gt/2.png")  #ground truth

image = TF.to_tensor(image)
image.unsqueeze_(0)
print(image.shape)
trimap = TF.to_tensor(trimap)
trimap.unsqueeze_(0)
gt_matte = TF.to_tensor(gt_matte)
gt_matte.unsqueeze_(0)

#dataloader = CREATE_YOUR_DATALOADER(bs)     # NOTE: please finish this function

for epoch in range(0, epochs):
    #for idx, (image, trimap, gt_matte) in enumerate(dataloader):
    semantic_loss, detail_loss, matte_loss = supervised_training_iter(modnet, optimizer, image, trimap, gt_matte)
    #lr_scheduler.step()

@ZHKKKe

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.
Please try to resize the input image to make sure its width/height can be divided by 32.
