### ISSUE TITLE
请问mobilenetv2_human_seg.ckpt在哪里下载

### ISSUE THREAD

**Issue by Unitshockresponse** [ZHKKKe/MODNet#77]

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

Please download it from [this link](https://drive.google.com/drive/folders/1umYmlCulvIFNaqPjwod1SayFmSRHziyR?usp=sharing).

**Comment by xafha** [comment]
@ZHKKKe 
你好，我正在复现Keras版本训练代码，请问你知道如何获取Keras版本的预训练ckpt（mobilenetv2_huamn_seg.ckpt）吗？

**Comment by ZHKKKe** [comment]
@xafha 
你好。这个模型从[这个仓库](https://github.com/thuyngch/Human-Segmentation-PyTorch)中获取的。目前似乎仅有PyTorch 版本。

**Comment by lailaiqq** [comment]
那个项目原作者好像不维护了，下载不到mmobilenetv2_human_seg.ckpt，学长有空的话可以分享一下你之前下载的吗？谢谢~

**Comment by ZHKKKe** [comment]
@lailaiqq [link](https://drive.google.com/drive/folders/1umYmlCulvIFNaqPjwod1SayFmSRHziyR)
