### ISSUE TITLE
Why calling the function contiguous()? self.bnorm(x[:, :self.bnorm_channels, ...].contiguous()) self.inorm(x[:, self.bnorm_channels:, ...].contiguous())

### ISSUE THREAD

**Issue by tianmingdu** [ZHKKKe/MODNet#81]
I am wondering the reason calling of contiguous() right before calling BatchNorm2d() or InstanceNorm2d. Could you shed some light on it?

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

The code of `IBNorm` is adopted from my previous project. The function `.contiguous()` is unnecessary in this project (but is necessary in my previous project). You can delete it.
