### ISSUE TITLE
How to get the composition result?

### ISSUE THREAD

**Issue by alairfan** [ZHKKKe/MODNet#83]
Thanks for sharing your awesome work! Now，I got the Predicted Froeground result smoothly, but how can I synthesize the PF result into another background?

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

Assum you have an original image `I`, a predicted alpha matte `a`, and a new background image `B`. You can composite a new image $I'$ as:
```
I' = a * I + (1 - a) * B,
```
where `*` is a element-wise multiplier. Note that the pixel values of `a` are between `[0, 1]`.

**Comment by zhanghonglishanzai** [comment]
Can you share a complete code project that replaces the original background with another background instead of a white background?

**Comment by ZHKKKe** [comment]
Taking our [Image Matting Colab Demo](https://colab.research.google.com/drive/1GANpbKT06aEFiW-Ssx0DQnnEADcXwQG6?usp=sharing#scrollTo=JOmYOHKfgQ5Y) as an example, please find the following code (in the section `4. Visualization`):
```
foreground = image * matte + np.full(image.shape, 255) * (1 - matte)
```
This code composites the foreground ` image * matte` on a white background `np.full(image.shape, 255) * (1 - matte)`. The only thing you need to do is upload your background image and use it to replace `np.full(image.shape, 255)`. The new code should be:
```
foreground = image * matte + YOUR_BACKGROUND * (1 - matte)
```
where `YOUR_BACKGROUND` is the desired new background. Note that `YOUR_BACKGROUND` should be a numpy array that has the same shape with `image` and `matte`.

Similarly, in our [Video Matting Colab Demo](https://colab.research.google.com/drive/1Pt3KDSc2q7WxFvekCnCLD8P0gBEbxm6J?usp=sharing#scrollTo=8pmCZ-kt4dU-), please find:
```
fg_np = matte_np * im_np + (1 - matte_np) * np.full(im_np.shape, 255.0)
```
and rewrite it as:
```
fg_np = matte_np * im_np + (1 - matte_np) * YOUR_BACKGROUND
```
