### ISSUE TITLE
请问如何复现基于Trimap free的DIM的？

### ISSUE THREAD

**Issue by semchan** [ZHKKKe/MODNet#87]
如题。是通过修改DIM的输入通道数来实现的吗？（去掉trimap通道，然后重新训练模型？）如果是的话，在测试的时候，也是计算全图的MSE和SAD，而不是仅计算未知区域的MSE和SAD的吗？谢谢您的解答。

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。

是的，我们直接去掉DIM的trimap通道，训练一个新模型。
测试时候metrics是在全图上计算的（对于使用trimap的DIM, 我们也是在全图计算metrics的）。

**Comment by semchan** [comment]
明白了。非常感谢您的回答。&nbsp;





Best Regards
 陈尧森，Sem Chan
Tel: 15208489326


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhanghan ***@***.***&gt;; 
发送时间: 2021年4月1日(星期四) 中午12:52
收件人: ***@***.***&gt;; 
抄送: "Sem ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZHKKKe/MODNet] 请问如何复现基于Trimap free的DIM的？ (#87)





 
Closed #87.
