### ISSUE TITLE
Small images in Colab and demo

### ISSUE THREAD

**Issue by benbro** [ZHKKKe/MODNet#88]
I've tested images with the [Colab demo](https://colab.research.google.com/drive/1GANpbKT06aEFiW-Ssx0DQnnEADcXwQG6?usp=sharing) and got weird result.
Am I doing something wrong?

![test1](https://user-images.githubusercontent.com/75841/112886160-3ae09880-90da-11eb-802f-c03e0792cf0f.png)
![test2](https://user-images.githubusercontent.com/75841/112886165-3caa5c00-90da-11eb-82eb-430be9f2e994.png)
![test3](https://user-images.githubusercontent.com/75841/112887130-74fe6a00-90db-11eb-81ed-c4347021237f.png)

https://images.app.goo.gl/qeYDhHrcNFwvfuVm9
https://images.app.goo.gl/d2K8PAQL5DY97YYJ6
https://images.app.goo.gl/b2smudtZ1dXn5dBX6

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.
It is strange.. I have tried the first image, and the result looks well. I have no idea about your results.
You may can try [this demo](https://gradio.app/g/modnet).

**Comment by benbro** [comment]
Now the result is good in both the Colab notebook and the web demo. I didn't change anything so I'm not sure why.
Thanks

**Comment by benbro** [comment]
This image looks weird in both Colab and the web demo:
https://images.app.goo.gl/xzhDTVhZM6zzFzgJ6

**Comment by benbro** [comment]
I think it depends on the image resolution. Maybe Google images first let you download a small thumbnail but if you wait you'll download the original image.
Do we need to upscale the image in the notebook and demo if it's too small?

Example:
Small:
![small](https://user-images.githubusercontent.com/75841/112943170-d2290880-9139-11eb-84d0-60300899213b.jpeg)
![small-result](https://user-images.githubusercontent.com/75841/112943298-fe448980-9139-11eb-99dc-ec1c5f5df959.png)

Big:
![big](https://user-images.githubusercontent.com/75841/112943191-d8b78000-9139-11eb-95cb-8baccb1a1f73.jpg)
![big-result](https://user-images.githubusercontent.com/75841/112943310-0270a700-913a-11eb-90e4-ba4bf6789716.png)

**Comment by ZHKKKe** [comment]
Oh... Yes.. The model will fail if the input image is too small. Please make sure the short side of the input image is larger than 256.

**Comment by benbro** [comment]
There is a problem in lines:
https://github.com/ZHKKKe/MODNet/blob/master/demo/image_matting/colab/inference.py#L90
https://github.com/ZHKKKe/MODNet/blob/master/demo/image_matting/colab/inference.py#L96
```python
im = F.interpolate(im, size=(im_rh, im_rw), mode='area')
```
I've tried adding recompute_scale_factor=True but it gives me another warning.
Any idea how to downscale with interpolate?

**Comment by ZHKKKe** [comment]
@benbro 
For your questions:
**Q1: Any idea how to upscale with interpolate?**
You may can use opencv to resize the image, then convert it to a torch Tensor.

**Is it possible to have a version of the model for smaller images? Maybe it'll run faster?**
The provided pre-trained model is trained by the samples of size `512x512`. Therefore, it may fail in small images.
If you use smaller images to train the model, it should be faster and more robust for small images.

**Comment by benbro** [comment]
Thanks
