### ISSUE TITLE
The default behavior for interpolate/upsample with float scale_factor changed

### ISSUE THREAD

**Issue by kaisark** [ZHKKKe/MODNet#89]
I ran into a Pytorch 1.8 warning message while running the demo on the Jetson Nano (Ubuntu 18). The program did complete though. 

(py36dl) me@jetsonnano:~/projects/MODNet$ python -m demo.video_matting.custom.run --video input-video/output-test1.avi.mp4 --fps 8
Get CMD Arguments...
Load pre-trained MODNet...
Use GPU...
Start matting...
  0%|                                                                                                            | 0/129 [00:00<?, ?it/s]                                                            /home/me/.virtualenvs/py36dl/lib/python3.6/site-packages/torch/nn/functional.py:3500: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. "The default behavior for interpolate/upsample with float scale_factor changed "
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 129/129 [01:46<00:00,  1.22it/s]
Save the result video to input-video/output-test1.avi_fg.mp4

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.
This is a warning from the PyTorch package. 
We do not validate the code with PyTorch > 1.5. Will this warning cause any problem in the output?
