### ISSUE TITLE
关于soc部分训练的问题

### ISSUE THREAD

**Issue by mingqizhang** [ZHKKKe/MODNet#9]
作者您好，对于soc训练这部分有些疑问，想请教一下。
1. 对于下面这个损失函数，以前面的l2损失为例，此时两个输入都是网络的输出结果，那么在做反向传播的时候，梯度是从两个输出同时传进去的吗，还是说会固定第二项。
![image](https://user-images.githubusercontent.com/28778038/101754103-549ba700-3b0e-11eb-9308-fed83cedf273.png)
2. 将M复制给M‘后，M’在后面权重是一直不变的吗？
3. 我对于soc的理解是，Lcons损失由于是自监督训练，会导致ap向sp和dp靠近，但由于sp是模糊的，那么会导致ap也变的模糊。此时加个Ldd来限制ap朝模糊的方向发展。但是如果前面训练好的M网络对于新域的视频数据预测的很差，那么结果会不会朝不好的方向发展呢？

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。

对于你的问题：

**Q1: 那么在做反向传播的时候，梯度是从两个输出同时传进去的吗**
梯度会从两个项传回去。以前面的l2损失为例，在实现时候需要将这个l2损失拆解为两项进行计算。每一项中需要detach其中一个网络输出作为标签计算梯度，否则，PyTorch会返回错误。

**Q2: 将M复制给M‘后，M’在后面权重是一直不变的吗**
时的， M' 在SOC中只是为保持细节提供一定的约束，它的权重始终固定。

**Q3: 如果前面训练好的M网络对于新域的视频数据预测的很差，那么结果会不会朝不好的方向发展呢？**
我们发现，在Matting中，网络对新域的视频数据预测的很差主要表现在人像语义估计上。细节估计可以被看作一个以人像语义为先验的low-level的视觉任务，通常，将网络应用在新数据域上依旧可以较好的处理细节。
