### ISSUE TITLE
量化指標MAD計算

### ISSUE THREAD

**Issue by peter31726** [ZHKKKe/MODNet#97]
感謝作者公布source code，我有幾個疑問想詢問

1. 請問您論文中Table.3的MAD量化數據怎麼計算的?

我目前寫法如下
def compute_sad(pred, alpha):
    pred = pred.cpu().numpy()
    alpha = alpha.cpu().numpy()

    diff = np.abs(pred - alpha)
    return np.sum(diff) / 1000

您的算法是alpha與output算絕對值距離loss，然後除以整張圖像大小(512x512) 再與整個測試資料集平均嗎?

2. Table.3 數據是訓練資料使用AMD的train擴張十倍並對AMD資料集中的test資料做計算嗎?  還是整個資料集(包含訓練資料)?
據我所知AMD test有50張alpha圖，在論文Appendix B中有說明是每張alpha 擴張十倍
也就是說table3的數據是跑500張平均出來的數值嗎?  

3. the models pretrained on the SPS [42] dataset. 指的就是mobilenetv2_human_seg.ckpt 權重檔?

請作者幫忙提點，謝謝

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。

对于你的问题：
1. 你的计算方式是以往论文中使用的`SAD (sum absolute difference)`指标。由于`SAD`的值较大，以往方法使用`1/1000`作为系数以缩小`SAD`. 由于我们测试集中不同图片的分辨率差异较大，所以我们采用更常见的`MAD (mean absolute difference)`. 在你的代码中，请将`return np.sum(diff) / 1000`改为`return np.mean(diff)`以获得`MAD`.
2. 我们的训练是在私有数据集上进行的。我们将`AMD train/test` 里所有的人像图片选出来合成背景作为测试集。
3. 是的。

**Comment by ppf-hhh** [comment]
> * 我们的训练是在私有数据集上进行的。我们将`AMD train/test` 里所有的人像图片选出来合成背景作为测试集。



> 你好，感谢你的关注。
> 
> 对于你的问题：
> 
> 1. 你的计算方式是以往论文中使用的`SAD (sum absolute difference)`指标。由于`SAD`的值较大，以往方法使用`1/1000`作为系数以缩小`SAD`. 由于我们测试集中不同图片的分辨率差异较大，所以我们采用更常见的`MAD (mean absolute difference)`. 在你的代码中，请将`return np.sum(diff) / 1000`改为`return np.mean(diff)`以获得`MAD`.
> 2. 我们的训练是在私有数据集上进行的。我们将`AMD train/test` 里所有的人像图片选出来合成背景作为测试集。
> 3. 是的。

作者你好, 我这边挑选出AMD中`train/test`所有人像图片，每一个前景对应COCO中的10张背景（COCO中不包含人像的图片），利用`modnet_photographic_portrait_matting.ckpt`模型生成每一张图片的alpha，通过下面公式计算每一张图的MSE和MAD：
> def compute_mse(pred, gt):
>     error_map = (pred/255.0-gt/255.0)**2
>     return np.mean(error_map)

> def compute_mse(pred, gt):
>     error_map = np.abs((pred/255.0-gt/255.0))
>     return np.mean(error_map)
然后对所有的图片求平均，结果是0.031和0.044，这个结果太差了，你能给我一些建议吗？

**Comment by ppf-hhh** [comment]
> 感謝作者公布source code，我有幾個疑問想詢問
> 
> 1. 請問您論文中Table.3的MAD量化數據怎麼計算的?
> 
> 我目前寫法如下
> def compute_sad(pred, alpha):
> pred = pred.cpu().numpy()
> alpha = alpha.cpu().numpy()
> 
> ```
> diff = np.abs(pred - alpha)
> return np.sum(diff) / 1000
> ```
> 
> 您的算法是alpha與output算絕對值距離loss，然後除以整張圖像大小(512x512) 再與整個測試資料集平均嗎?
> 
> 1. Table.3 數據是訓練資料使用AMD的train擴張十倍並對AMD資料集中的test資料做計算嗎?  還是整個資料集(包含訓練資料)?
>    據我所知AMD test有50張alpha圖，在論文Appendix B中有說明是每張alpha 擴張十倍
>    也就是說table3的數據是跑500張平均出來的數值嗎?
> 2. the models pretrained on the SPS [42] dataset. 指的就是mobilenetv2_human_seg.ckpt 權重檔?
> 
> 請作者幫忙提點，謝謝

您好，打扰您了，请问你有跑出Table.3 MODNet的结果吗？我用AMD的训练、测试人像前景和来自COCO的背景（不包含人像）按照1：10合成一个测试集，但是用MODNet测试的MSE指标不太好？如果您有跑出Table.3的结果，我们可以交流一下吗？

**Comment by ppf-hhh** [comment]
> @ppf-hhh
> 你好，论文中table 3采用的网络不是使用AMD的训练集训练的，是在我们私有的数据集（和Table 1/2一样的）上训练的。

可能我没有表述清楚，我的意思是我用AMD的训练集和测试集里面所有的人像前景构造类似table 3的测试集，然后模型用的是训练好的MODNet（github下提供的modnet_photographic_portrait_matting.ckpt）去做测试，测试代码用的是demo/image_matting/colab/inference.py ，测出来的结果和论文里面有一定的差距，我想知道论文中table 3使用的背景图片是从Open Image里面随机挑选的吗？table 3中用AMD数据构造的测试集可以提供一下吗？

**Comment by ZHKKKe** [comment]
@ppf-hhh 
你好，对于你的问题：
**Q1: 我想知道论文中table 3使用的背景图片是从Open Image里面随机挑选的吗**
对的。

**Q2: table 3中用AMD数据构造的测试集可以提供一下吗?**
很抱歉目前我没有权限分享除Github上已有内容外的相关资料。
