### ISSUE TITLE
使用预训练模型微调问题

### ISSUE THREAD

**Issue by upperblacksmith** [ZHKKKe/MODNet#98]
首先非常感谢作者能够将部分源码开源，salute。
    
  有以下几个问题期待解答：

1.使用modnet_photographic_portrait_matting.ckpt测试自己的数据，下图是例子，对脸部做了脱敏处理
如图左边是原图，中间是模型得到的alpha图，右边是合成的证照图像，图像大小为375*472，输入到模型之前短边放大到512，并保持宽高比不变。
所产生的问题是人像区域有部分前景（包括脸部和头发区域）被误分成背景，原图背景复杂，得到的alpha图前景和背景过渡区域精度不够，以上问题是否由于背景复杂所致或者说是由于原图尺寸太小缩放后导致的

![99999](https://user-images.githubusercontent.com/34127965/116175248-88384000-a742-11eb-9042-d0c75e5f93af.JPG)

2.使用自己的数据集对modnet_photographic_portrait_matting.ckpt进行微调，微调后的效果并不是很好，是否有可能是因为用于微调的数据和作者原有数据集之间的差异性太大所导致，证照背景统一为办公场所的自然场景。

希望能得到作者的解答和建议，谢谢。

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。
对于你的问题：
1. 我们开源的模型主要用于研究目的，使用的训练数据较少。因此它在一些样例上会出现不稳定（错误）的结果。你可以尝试输入原始尺寸的图片（需要做一个resize，保证边长可以被32整除）。
2. 从你给出的示例来看，SOC策略应该是能够将模型迁移到对应的数据域上的，即，可以解决上述前景出现空洞的问题。可能是由于具体的实现。请尝试使用我们提供的训练代码，按照论文中提供的超参数来调整训练策略。

**Comment by upperblacksmith** [comment]
> 你好，感谢你的关注。
> 对于你的问题：
> 
> 1. 我们开源的模型主要用于研究目的，使用的训练数据较少。因此它在一些样例上会出现不稳定（错误）的结果。你可以尝试输入原始尺寸的图片（需要做一个resize，保证边长可以被32整除）。
> 2. 从你给出的示例来看，SOC策略应该是能够将模型迁移到对应的数据域上的，即，可以解决上述前景出现空洞的问题。可能是由于具体的实现。请尝试使用我们提供的训练代码，按照论文中提供的超参数来调整训练策略。

使用soc策略时，模型输入大小是否需要与无监督训练前的trained_model保持同样的输入大小？

**Comment by ZHKKKe** [comment]
@upperblacksmith 
不需要的。SOC时的输入大小可以根据实际应用需要进行调整。但是不可以差异过大（例如，训练阶段使用384x384, 而SOC使用2048x2048）。

**Comment by ZHKKKe** [comment]
@upperblacksmith 
你好，可以尝试我们在这个[网站发布](https://sight-x.cn/portrait_matting/)的商业模型，获取可以解决你的问题。
