### ISSUE TITLE
当有黑色背景时,效果不准

### ISSUE THREAD

**Issue by yangjian1218** [ZHKKKe/MODNet#99]
当背景有黑色物体跟头或者身体接触时,也会被抠图到身体一部分.我拿同一张图放到百度的人像分割里,他们可以分割出黑色背景. 有什么办法可以解决此问题吗?

**Comment by ZHKKKe** [comment]
你好，感谢你的关注。这主要可能由以下原因造成：
1. 网络的大小。MODNet专注于视频抠像，因此使用较小的网络结构，这一定程度上牺牲了性能。在我们的实验中，采用更大的backbone网络，例如ResNet-101, 会带来较大的性能提升。一般商用图片抠像解决方案会采用较大的网络，因为通过调用API实现的图像处理不需要满足实时性。
2. 训练集的大小。由于发布的模型是作为研究目的，我们仅使用3000个标注数据进行了训练。而商业软件一般会使用十万甚至百万的标注数据进行训练，因此往往可以覆盖更多的复杂，比如你所展示的例子。我们的实验也表明在大数据集上训练的模型可以获得很大的性能提升。

**Comment by syfbme** [comment]
> 你好，感谢你的关注。这主要可能由以下原因造成：
> 
> 1. 网络的大小。MODNet专注于视频抠像，因此使用较小的网络结构，这一定程度上牺牲了性能。在我们的实验中，采用更大的backbone网络，例如ResNet-101, 会带来较大的性能提升。一般商用图片抠像解决方案会采用较大的网络，因为通过调用API实现的图像处理不需要满足实时性。
> 2. 训练集的大小。由于发布的模型是作为研究目的，我们仅使用3000个标注数据进行了训练。而商业软件一般会使用十万甚至百万的标注数据进行训练，因此往往可以覆盖更多的复杂，比如你所展示的例子。我们的实验也表明在大数据集上训练的模型可以获得很大的性能提升。

你好：
可以分享下ResNet-101作为backbone的预训练模型吗？我使用了ResNet-101训练，但是效果不理想，考虑是否是因为没有预训练

**Comment by ZHKKKe** [comment]
@syfbme 你好，请从 https://github.com/thuyngch/Human-Segmentation-PyTorch 获取预训练模型。目前似乎没有ResNet-101的版本。
